import type { NativeAction, NativeReceipt } from '../hand/protocol.js';
export type RecoveryAction = NativeAction | { kind:'focus_click';x:number;y:number;duration_ms:number };
export interface RecoveryTarget {pid:number;start_ticks:string;hwnd:string;class:string;executable:string}
export interface RecoverySource {observation_id:string;capture_sha256:string;width:number;height:number;observation_path:string}
export interface RecoverySafety {allowed:boolean;reason?:string;visible:boolean;minimized:boolean;focused:boolean;client_fully_visible:boolean;user_idle_ms:number;idle_threshold_ms:number;occluders:unknown[];[key:string]:unknown}
export interface RecoveryWindow {client_width:number;client_height:number;dpi:number;focused:boolean;visible:boolean;minimized:boolean;recovery_safety:RecoverySafety}
export interface RecoveryCapture {file:string;sha256:string;width:number;height:number;started_windows_qpc_ms:number;finished_windows_qpc_ms:number;method:string}
export interface RecoveryOcrItem {text:string;x:number;y:number;width:number;height:number}
export interface RecoverySelectedCharacter {verified:boolean;source:"calibrated_cv";reason:string;calibration_sha256:string;reference_sha256:string;layout_width:number;layout_height:number;observation_id:string;capture_sha256:string;regions:Array<{region:string;mean_abs_error:number;fraction_above_24:number;max_mean_abs_error:number;max_fraction_above_24:number;matched:boolean}>;name?:string;class?:"warrior";faction?:"alliance";safe_focus_point?:{x:number;y:number}}
export interface RecoveryTutorialCv {verified:boolean;source:"calibrated_cv";kind:"talk_jaina";npc_name:string;calibration_sha256:string;reference_sha256:string;regions:Array<{region:string;matched:boolean;mask_iou?:number;min_iou?:number;mean_abs_error?:number;fraction_above_24?:number;max_mean_abs_error?:number;max_fraction_above_24?:number}>;action_point:{x:number;y:number};safe_focus_point:{x:number;y:number};observation_id:string;capture_sha256:string}
export interface RecoveryObservation {schema_version:1;status:'observed';session_id:1;observation_id:string;target:RecoveryTarget;window:RecoveryWindow;capture:RecoveryCapture;selected_character?:RecoverySelectedCharacter;tutorial_cv?:RecoveryTutorialCv;ocr:{status:'available'|'unknown';items:RecoveryOcrItem[];reason?:string;raw_text_retained:false};started_windows_qpc_ms:number;finished_windows_qpc_ms:number}
export type BridgeRequest = {version:1;op:'discover'} | {version:1;op:'launch_battlenet'} | {version:1;op:'observe';target:RecoveryTarget} | {version:1;op:'input';target:RecoveryTarget;action:RecoveryAction;source:RecoverySource} | {version:1;op:'launch_wow';target:RecoveryTarget;source:RecoverySource};
export interface BridgeResult {schema_version:1;status:string;reason?:string|null;session_id:1;started_windows_qpc_ms?:number;finished_windows_qpc_ms?:number;processes?:Array<{kind:'wow'|'battle_net';target:RecoveryTarget;window:RecoveryWindow}>;process_inventory?:Array<{kind:'wow'|'battle_net';pid:number;start_ticks:string;session_id:1;executable:string;visible_nonminimized_windows:number}>;launcher_candidates?:Array<{executable:string;signature_status:string;publisher:string;sha256:string;allowed:boolean}>;target?:RecoveryTarget;window?:RecoveryWindow;capture?:RecoveryCapture;ocr?:RecoveryObservation['ocr'];observation_id?:string;native_raw_file?:string;native_raw_sha256?:string;native_lines?:unknown[];receipts?:NativeReceipt[];release_confirmed?:boolean;input_sent?:boolean;effect_status?:'unknown'}
export interface RecoveryFrame {observation:RecoveryObservation;source:RecoverySource;requested_at_ms:number;received_at_ms:number}
export interface RecoveryButton {id:'enter_world'|'disconnect_ack'|'reconnect'|'launcher_play'|'dialogue_continue'|'dialogue_finish'|'npc_interact';text:string;x:number;y:number;width:number;height:number}
export type RecoveryScene = 'world'|'character_select'|'disconnected'|'launcher'|'loading'|'login'|'blocked_auth'|'blocked_terms'|'blocked_update'|'unknown';
/** Review evidence must cite this original frame. It cannot make a previous frame fresh. */
export interface RecoveryReview {version:1;source:RecoverySource;target:RecoveryTarget;kind:'human_reviewed';reviewed_at:string;scene:RecoveryScene;buttons:RecoveryButton[];safe_focus_point?:{x:number;y:number};selected_row?:{rect:{x:number;y:number;width:number;height:number};character:string;class:'warrior';faction:'alliance';gold_selected:boolean;alliance_glyph:boolean;evidence:'human_reviewed_same_capture'};first_objective?:'与吉安娜·普罗德摩尔交谈';conversation_confirmed?:boolean;tutorial_step_changed?:boolean}
export interface RecoveryInterpretation {scene:RecoveryScene;source_kind:'ocr'|'human_reviewed';buttons:RecoveryButton[];selected_character:{name:string;class:'warrior';faction:'alliance'}|null;safe_focus_point:{x:number;y:number}|null;reason:string}
export interface RecoveryEvent {sequence:number;at_ms:number;kind:string;data:unknown}
export interface RecoveryResult {protocol:'wow-session-recovery';version:1;run_id:string;mode:'offline'|'live';command:'recover'|'launch';status:'completed'|'blocked'|'cancelled'|'failed';reason:string;elapsed_ms:number;action_attempts:number;input_issued:number;input_count_scope:'known'|'lower_bound';effects_confirmed:number;release:'confirmed'|'unconfirmed';goal_effect:'unverified'|'world_confirmed';models:{visual:0;jev:0;brain:0};decision_owner:'code_state_machine_root_supervised';evidence_scope:'simulated_ports'|'interactive_bridge';events:RecoveryEvent[];trace:import('../benchmark/trace.js').TraceRecord[];last_observation:RecoverySource|null}
