import test from 'node:test';
import assert from 'node:assert/strict';
import {RecoveryOrchestrator,type RecoveryPorts} from '../src/recovery/orchestrator.js';
import {interpretRecovery,sourceFor} from '../src/recovery/recognition.js';
import type {BridgeRequest,BridgeResult,RecoveryFrame,RecoveryObservation,RecoveryReview,RecoveryScene,RecoveryTarget} from '../src/recovery/types.js';
const wow:RecoveryTarget={pid:42,start_ticks:'638900000000000000',hwnd:'0x1234',class:'GxWindowClassD3d',executable:'C:\\Games\\World of Warcraft\\_retail_\\Wow.exe'};
const launcher:RecoveryTarget={pid:43,start_ticks:'638900000000000001',hwnd:'0x5678',class:'Chrome_WidgetWin_0',executable:'C:\\Battle.net\\Battle.net.exe'};
function harness(options:{scene?:RecoveryScene;focused?:boolean;idle?:number;covered?:boolean;wrongCharacter?:boolean;noReview?:boolean;noWow?:boolean;noLauncher?:boolean;launchFailure?:boolean;reuseFrame?:boolean;stale?:boolean;release?:boolean;noEffect?:boolean;inputHang?:boolean;reviewTamper?:boolean;postCaptureOld?:boolean}={}){
  let time=0,seq=0,scene=options.scene??'world',focused=options.focused??true,hasWow=!options.noWow,hasLauncher=!options.noLauncher,conversation=false,objective=true,lastObservation:RecoveryObservation|null=null;
  const requests:BridgeRequest[]=[],releaseCalls:string[]=[],events:unknown[]=[];
  const observation=(target:RecoveryTarget):RecoveryObservation=>{const id=options.reuseFrame?'obs-static':`obs-${seq++}`;const text=target.pid===launcher.pid?'进入游戏':scene==='character_select'?'进入世界':scene==='disconnected'?'重新连接':scene==='blocked_auth'?'验证码':scene==='blocked_update'?'正在更新':scene==='blocked_terms'?'用户协议':scene==='loading'?'载入中':'与吉安娜·普罗德摩尔交谈';return{schema_version:1,status:'observed',session_id:1,observation_id:id,target,window:{client_width:1000,client_height:800,dpi:96,focused,visible:true,minimized:false,recovery_safety:{allowed:true,visible:true,minimized:false,focused,client_fully_visible:!options.covered,user_idle_ms:options.idle??6000,idle_threshold_ms:5000,occluders:options.covered?[{hwnd:'0x9999'}]:[]}},capture:{file:'client.png',sha256:String(seq%10).repeat(64),width:1000,height:800,started_windows_qpc_ms:options.postCaptureOld&&conversation?1:10000+time,finished_windows_qpc_ms:options.postCaptureOld&&conversation?2:10001+time,method:'printwindow'},ocr:{status:'available',items:[{text,x:100,y:200,width:200,height:40}],raw_text_retained:false},started_windows_qpc_ms:options.postCaptureOld&&conversation?1:10000+time,finished_windows_qpc_ms:10002+time};};
  const ports:RecoveryPorts={now:()=>time,sleep:async ms=>{time+=ms;},append:async e=>{events.push(e);},release:async reason=>{releaseCalls.push(reason);return{release:options.release===false?'unconfirmed':'confirmed'};},call:async request=>{
    requests.push(structuredClone(request));time++;if(request.op==='discover')return{schema_version:1,status:'discovered',session_id:1,processes:[...(hasWow?[{kind:'wow' as const,target:wow,window:observation(wow).window}]:[]),...(hasLauncher?[{kind:'battle_net' as const,target:launcher,window:observation(launcher).window}]:[])],launcher_candidates:[{executable:launcher.executable,signature_status:'Valid',publisher:'Blizzard',sha256:'a'.repeat(64),allowed:true}]};
    if(request.op==='observe'){if(options.stale)time+=15001;lastObservation=observation(request.target);time+=2;return lastObservation;}
    if(request.op==='launch_battlenet'){hasLauncher=true;return{schema_version:1,status:'launched',session_id:1};}
    if(request.op==='launch_wow'){if(options.launchFailure)return{schema_version:1,status:'blocked',reason:'launcher_cli_failed',session_id:1};hasWow=true;scene='character_select';return{schema_version:1,status:'launched',session_id:1};}
    if(options.inputHang)return new Promise(()=>{});
    const start=10000+time;time+=60;if(request.action.kind==='focus_click')focused=true;else if(request.target.pid===launcher.pid){hasWow=true;scene='character_select';}else if(scene==='character_select')scene='world';else if(scene==='disconnected')scene='character_select';else if(!options.noEffect){conversation=true;objective=false;}
    return{schema_version:1,status:'input_released',session_id:1,release_confirmed:true,input_sent:true,effect_status:'unknown',receipts:[{protocol:'wow-input',version:1,type:'receipt',id:'native-action',session_id:'6d12af20-0011-4222-8333-012345678901',op:'execute',status:'completed',input:{status:'released',events_requested:2,events_inserted:2,released:true},effect:{status:'unknown'},timing:{clock:'windows_qpc',started_ms:start,finished_ms:10000+time},input_timing:{clock:'windows_qpc',first_send_started_ms:start+.1,first_send_finished_ms:start+.2,last_send_finished_ms:10000+time-.1},local_clock:{domain:'windows-qpc',at_ms:10000+time}}]};
  },...(!options.noReview?{review:async(frame:RecoveryFrame):Promise<RecoveryReview>=>({version:1,kind:'human_reviewed',source:options.reviewTamper?{...frame.source,capture_sha256:'f'.repeat(64)}:frame.source,target:frame.observation.target,reviewed_at:'2026-10-06T00:00:00Z',scene:frame.observation.target.pid===launcher.pid?'launcher':scene,buttons:[{id:frame.observation.target.pid===launcher.pid?'launcher_play':scene==='character_select'?'enter_world':scene==='disconnected'?'reconnect':'npc_interact',text:'same frame point',x:480,y:650,width:40,height:40}],safe_focus_point:{x:500,y:250},selected_row:{rect:{x:400,y:100,width:500,height:100},character:options.wrongCharacter?'另一个角色':'小啊',class:'warrior',faction:'alliance',gold_selected:true,alliance_glyph:true,evidence:'human_reviewed_same_capture'},...(objective?{first_objective:'与吉安娜·普罗德摩尔交谈' as const}:{}),conversation_confirmed:conversation,tutorial_step_changed:conversation})}:{})};
  const runner=new RecoveryOrchestrator({runId:'test-recovery',directory:'/tmp/recovery-test-not-written',command:'recover',mode:'offline',authorized:true,targetCharacter:'小啊'},ports);
  return{runner,ports,requests,releaseCalls,events,get time(){return time;},set time(v:number){time=v;},get last(){return lastObservation;}};
}
test('first Jaina conversation runs one bounded right click then stops at independent transition',async()=>{const h=harness();const r=await h.runner.run();assert.equal(r.status,'completed');assert.equal(r.goal_effect,'first_conversation_confirmed');assert.equal(r.action_attempts,1);assert.equal(r.input_issued,1);assert.equal(r.effects_confirmed,1);assert.equal(r.release,'confirmed');const action=h.requests.find(q=>q.op==='input')!;assert.equal(action.op,'input');if(action.op==='input'){assert.equal(action.action.kind,'mouse_click');if(action.action.kind==='mouse_click')assert.equal(action.action.button,'right');}assert.deepEqual(r.models,{visual:0,jev:0,brain:0});assert.equal(h.releaseCalls.length,1);});
test('launch only stops in observed world without NPC action',async()=>{const h=harness({scene:'character_select'});const runner=new RecoveryOrchestrator({runId:'launch',directory:'/tmp/launch-test',command:'launch',mode:'offline',authorized:true,targetCharacter:'小啊'},h.ports);const r=await runner.run();assert.equal(r.status,'completed');assert.equal(r.goal_effect,'world_confirmed');assert.equal(r.action_attempts,1);assert.equal(r.input_issued,1);});
test('one safe idle focus click requires whole client visibility and post foreground',async()=>{const h=harness({focused:false});const r=await h.runner.run();assert.equal(r.status,'completed');assert.equal(r.action_attempts,2);assert.equal(h.requests.filter(q=>q.op==='input'&&q.action.kind==='focus_click').length,1);assert.ok(r.events.some(e=>e.kind==='effect_confirmed'&&(e.data as {reason:string}).reason==='foreground_confirmed'));});
test('recent input, occlusion and non idle safety each block before any native input',async()=>{for(const options of [{focused:false,idle:4999},{focused:false,covered:true}]){const h=harness(options);const r=await h.runner.run();assert.equal(r.status,'blocked');assert.equal(r.input_issued,0);assert.equal(h.requests.filter(q=>q.op==='input').length,0);}});
test('wrong selected character is blocked despite a visible enter-world button',async()=>{const h=harness({scene:'character_select',wrongCharacter:true});const r=await h.runner.run();assert.equal(r.status,'blocked');assert.match(r.reason,/selected_alliance_warrior/);assert.equal(r.input_issued,0);});
test('whole-screen name/class/faction OCR does not establish the selected row or gold/glyph',async()=>{const h=harness({scene:'character_select',noReview:true});const old=h.ports.call;h.ports.call=async(...args)=>{const result=await old(...args);if(result.status==='observed')result.ocr!.items.push(...['小啊','战士','联盟'].map((text,i)=>({text,x:20+i*200,y:400+i*80,width:100,height:30})));return result;};const r=await h.runner.run();assert.equal(r.status,'blocked');assert.equal(r.input_issued,0);});
test('credential, terms and installation signals outrank reviewed scene and never receive input',async()=>{for(const scene of ['blocked_auth','blocked_terms','blocked_update'] as const){const h=harness({scene});const r=await h.runner.run();assert.equal(r.status,'blocked');assert.equal(h.requests.filter(q=>q.op==='input').length,0);assert.match(r.reason,/required/);}});
test('current review cannot relabel another capture as reviewed evidence',async()=>{const h=harness({reviewTamper:true});const r=await h.runner.run();assert.equal(r.status,'failed');assert.match(r.reason,/review_source_binding/);assert.equal(r.input_issued,0);});
test('stale bridge capture and reused observation identity prevent a second action',async()=>{const stale=harness({stale:true});assert.match((await stale.runner.run()).reason,/source_capture_age/);assert.equal(stale.requests.filter(q=>q.op==='input').length,0);const reused=harness({reuseFrame:true,scene:'character_select'});assert.match((await reused.runner.run()).reason,/identity_reused/);assert.equal(reused.requests.filter(q=>q.op==='input').length,1);});
test('input sent and independent conversation effect stay distinct on missing transition',async()=>{const h=harness({noEffect:true});const r=await h.runner.run();assert.equal(r.status,'blocked');assert.equal(r.input_issued,1);assert.equal(r.effects_confirmed,0);assert.equal(r.goal_effect,'unverified');assert.match(r.reason,/effect_unconfirmed/);});
test('post input source predating native completion cannot confirm game effect',async()=>{const h=harness({postCaptureOld:true});const r=await h.runner.run();assert.equal(r.status,'blocked');assert.equal(r.input_issued,1);assert.equal(r.effects_confirmed,0);assert.match(r.reason,/post_input_effect_source/);});
test('launch chain observes Battle.net, falls back to current CV play button only after CLI failure',async()=>{const h=harness({noWow:true,noLauncher:true,launchFailure:true});const r=await h.runner.run();assert.equal(r.status,'completed');assert.deepEqual(h.requests.filter(q=>q.op==='launch_battlenet'||q.op==='launch_wow').map(q=>q.op),['launch_battlenet','launch_wow']);assert.ok(h.requests.some(q=>q.op==='input'&&q.target.pid===launcher.pid));assert.equal(r.action_attempts,5);});
test('loading remains finite under per phase virtual time and emits no speculative input',async()=>{const h=harness({scene:'loading'});const r=await h.runner.run();assert.equal(r.status,'blocked');assert.match(r.reason,/loading_deadline/);assert.equal(r.input_issued,0);});
test('external cancel while input is pending has finite cleanup and never claims release or effect',async()=>{const h=harness({inputHang:true,release:false}),controller=new AbortController();setTimeout(()=>controller.abort('offline_test_cancel'),15);const r=await h.runner.run(controller.signal);assert.equal(r.status,'cancelled');assert.equal(r.release,'unconfirmed');assert.equal(r.input_count_scope,'lower_bound');assert.equal(r.effects_confirmed,0);});
test('port which never returns is bounded independently of its abort cooperation',async()=>{const h=harness();h.ports.call=async()=>new Promise(()=>{});const runner=new RecoveryOrchestrator({runId:'timeout',directory:'/tmp/recovery-timeout',command:'recover',mode:'offline',authorized:true,targetCharacter:'小啊',stageTimeoutMs:10},h.ports);const start=performance.now(),r=await runner.run();assert.equal(r.status,'blocked');assert.ok(performance.now()-start<500);assert.match(r.reason,/deadline/);});
test('action lease stops after one finite action and preserves issued evidence',async()=>{const h=harness({scene:'character_select'});const runner=new RecoveryOrchestrator({runId:'budget',directory:'/tmp/recovery-budget',command:'recover',mode:'offline',authorized:true,targetCharacter:'小啊',maxActions:1},h.ports);const r=await runner.run();assert.equal(r.status,'blocked');assert.match(r.reason,/action_budget/);assert.equal(r.action_attempts,1);assert.equal(r.input_issued,1);});
test('invalid authorization, character and unbounded options reject before ports',()=>{const h=harness();for(const patch of [{authorized:false},{targetCharacter:'别的角色'},{maxDurationMs:180001},{stageTimeoutMs:30001},{maxActions:9},{clickDurationMs:101},{maxObservationAgeMs:15001}])assert.throws(()=>new RecoveryOrchestrator({runId:'invalid',directory:'/tmp/invalid',command:'recover',mode:'offline',authorized:true,targetCharacter:'小啊',...patch},h.ports),/recovery_/);});
test('calibrated selected row requires same current image, layout and all region matches',async()=>{const h=harness({scene:'character_select',noReview:true});await h.ports.call({version:1,op:'observe',target:wow},'/tmp/source',new AbortController().signal);const obs=h.last!;obs.selected_character={verified:true,source:'calibrated_cv',reason:'matched',calibration_sha256:'a'.repeat(64),reference_sha256:'b'.repeat(64),layout_width:1000,layout_height:800,observation_id:obs.observation_id,capture_sha256:obs.capture.sha256,regions:[{region:'selected_identity_and_alliance',mean_abs_error:0,fraction_above_24:0,max_mean_abs_error:5,max_fraction_above_24:.05,matched:true}],name:'小啊',class:'warrior',faction:'alliance'};const f={observation:obs,source:sourceFor(obs,'/tmp/source'),requested_at_ms:0,received_at_ms:1};assert.equal(interpretRecovery(f).selected_character?.name,'小啊');obs.selected_character.capture_sha256='f'.repeat(64);assert.throws(()=>interpretRecovery(f),/calibrated_identity_source_binding/);});
test('automatic source calibrated selected character follows the normal enter-world path without per-frame review',async()=>{const h=harness({scene:'character_select',noReview:true});const original=h.ports.call;h.ports.call=async(...args)=>{const result=await original(...args);if(result.status==='observed'&&result.ocr!.items.some(i=>i.text==='进入世界')){const obs=result as unknown as RecoveryObservation;obs.selected_character={verified:true,source:'calibrated_cv',reason:'all_regions_matched',calibration_sha256:'a'.repeat(64),reference_sha256:'b'.repeat(64),layout_width:1000,layout_height:800,observation_id:obs.observation_id,capture_sha256:obs.capture.sha256,regions:[{region:'selected_identity',mean_abs_error:0,fraction_above_24:0,max_mean_abs_error:5,max_fraction_above_24:.05,matched:true}],name:'小啊',class:'warrior',faction:'alliance',safe_focus_point:{x:500,y:250}};}return result;};const runner=new RecoveryOrchestrator({runId:'auto',directory:'/tmp/recovery-auto',command:'launch',mode:'offline',authorized:true,targetCharacter:'小啊'},h.ports);const result=await runner.run();assert.equal(result.status,'completed');assert.equal(result.input_issued,1);assert.equal(result.goal_effect,'world_confirmed');});
test('automatic calibrated tutorial right-click stops when a separate left dialogue title and control appear',async()=>{const h=harness({noReview:true});const original=h.ports.call;let observations=0;h.ports.call=async(...args)=>{const result=await original(...args);if(result.status==='observed'){const obs=result as unknown as RecoveryObservation;if(++observations===1)obs.tutorial_cv={verified:true,source:'calibrated_cv',kind:'talk_jaina',npc_name:'吉安娜·普罗德摩尔',calibration_sha256:'a'.repeat(64),reference_sha256:'b'.repeat(64),regions:[{region:'jaina_and_first_instruction',mean_abs_error:0,fraction_above_24:0,max_mean_abs_error:5,max_fraction_above_24:.05,matched:true}],action_point:{x:500,y:550},safe_focus_point:{x:200,y:750},observation_id:obs.observation_id,capture_sha256:obs.capture.sha256};else obs.ocr.items=[{text:'吉安娜·普罗德摩尔',x:100,y:100,width:200,height:30},{text:'接受',x:100,y:600,width:60,height:30}];}return result;};const r=await h.runner.run();assert.equal(r.status,'completed');assert.equal(r.input_issued,1);assert.equal(r.effects_confirmed,1);assert.equal(h.requests.filter(q=>q.op==='input').length,1);});
test('shared bridge schema rejects arbitrary launch arguments, credential text and unsupported action shape',async()=>{const {loadRecoveryValidators}=await import('../src/recovery/bridge.js');const {fileURLToPath}=await import('node:url');const v=await loadRecoveryValidators(fileURLToPath(new URL('../..',import.meta.url)));assert.equal(v.request({version:1,op:'discover'}),true);for(const value of [{version:1,op:'launch_battlenet',executable:'C:\\evil.exe'},{version:1,op:'input',target:wow,source:{observation_id:'obs',capture_sha256:'a'.repeat(64),width:1000,height:800,observation_path:'/tmp/obs'},action:{kind:'text',text:'password'}},{version:1,op:'launch_wow',target:launcher,source:{observation_id:'obs',capture_sha256:'a'.repeat(64),width:1000,height:800,observation_path:'/tmp/obs'},arguments:['--anything']}])assert.equal(v.request(value),false);assert.equal(v.result({schema_version:1,status:'launched',session_id:0,input_sent:false,release_confirmed:false,effect_status:'unknown'}),false);});
test('pre-aborted runs touch no bridge port and still record independent release',async()=>{const h=harness();const c=new AbortController();c.abort('offline_pre_abort');const r=await h.runner.run(c.signal);assert.equal(r.status,'cancelled');assert.equal(h.requests.length,0);assert.equal(h.releaseCalls.length,1);});
test('CLI help is offline and absent authorization rejects before any output or desktop port',async()=>{const {recoveryMain}=await import('../src/recovery/cli.js');assert.match(JSON.stringify(await recoveryMain(['--help'])),/no cloud models/);await assert.rejects(recoveryMain(['recover','--run-dir','/tmp/not-created','--target-character','小啊']),/explicit_authorization/);});
test('an invisible/minimized existing Wow or Battle.net process stops rather than starting duplicates',async()=>{for(const kind of ['wow','battle_net'] as const){const h=harness({noWow:true,noLauncher:true});const original=h.ports.call;h.ports.call=async(...args)=>{const result=await original(...args);if(args[0].op==='discover')result.process_inventory=[{kind,pid:100,start_ticks:'638900000000000003',session_id:1,executable:kind==='wow'?wow.executable:launcher.executable,visible_nonminimized_windows:0}];return result;};const r=await h.runner.run();assert.equal(r.status,'blocked');assert.match(r.reason,/existing_.*process_requires_observe_not_relaunch/);assert.equal(h.requests.filter(q=>q.op==='launch_battlenet'||q.op==='launch_wow'||q.op==='input').length,0);}});
test('cold interactive bridge roundtrip and native capture are separate clocks and stages',async()=>{const h=harness();const r=await h.runner.run();assert.ok(r.trace.some(t=>t.kind==='span'&&t.stage==='bridge'&&t.start.domain==='simulation-monotonic'));assert.ok(r.trace.some(t=>t.kind==='span'&&t.stage==='capture'&&t.start.domain==='windows-qpc'&&t.meta.cold_bridge_excluded===true));assert.ok(r.trace.some(t=>t.kind==='span'&&t.stage==='native_input'));assert.equal(r.trace.filter(t=>t.kind==='span'&&['visual_model','brain','jev'].includes(t.stage)).length,0);});
test('actual bridge canonical auth/terms/update boxes block even when healthy Play remains visible behind dialog',async()=>{for(const word of ['协议','同意','许可','验证','身份验证','更新','修复','扫描']){const h=harness({noWow:true});const original=h.ports.call;h.ports.call=async(...args)=>{const result=await original(...args);if(result.status==='observed')result.ocr!.items.push({text:word,x:200,y:500,width:100,height:30});return result;};const r=await h.runner.run();assert.equal(r.status,'blocked',word);assert.match(r.reason,/required/,word);assert.equal(h.requests.filter(q=>q.op==='input'||q.op==='launch_wow').length,0,word);}});
test('actual retail waApplication Window class is accepted with the original exact PID/path binding',async()=>{const h=harness();const original=h.ports.call;h.ports.call=async(...args)=>{const result=await original(...args);if(result.processes)for(const p of result.processes)if(p.kind==='wow')p.target={...p.target,class:'waApplication Window'};if(result.target)result.target={...result.target,class:'waApplication Window'};return result;};const r=await h.runner.run();assert.equal(r.status,'completed');assert.equal(r.input_issued,1);});
test('accepted --exec request with no WoW effect falls back once to newly observed healthy Play',async()=>{const h=harness({noWow:true});const original=h.ports.call;let ignoreWow=true;h.ports.call=async(...args)=>{const result=await original(...args);if(args[0].op==='launch_wow')return{schema_version:1,status:'launched',session_id:1,reason:'launch_requested'};if(args[0].op==='discover'&&ignoreWow)result.processes=result.processes!.filter(p=>p.kind!=='wow');if(args[0].op==='input'&&args[0].target.pid===launcher.pid)ignoreWow=false;return result;};const r=await h.runner.run();assert.equal(r.status,'completed');assert.equal(h.requests.filter(q=>q.op==='launch_wow').length,1);assert.equal(h.requests.filter(q=>q.op==='input'&&q.target.pid===launcher.pid).length,1);assert.ok(r.events.some(e=>e.kind==='launcher_cli_effect'&&(e.data as {effect:string}).effect==='no_wow_observed_in_bounded_window'));});
test('cold Battle.net window appears after several process observations without a duplicate launch',async()=>{const h=harness({noWow:true,noLauncher:true});const original=h.ports.call;let afterLaunch=false,polls=0;h.ports.call=async(...args)=>{const result=await original(...args);if(args[0].op==='launch_battlenet')afterLaunch=true;if(args[0].op==='discover'&&afterLaunch&&polls++<3){result.processes=result.processes!.filter(p=>p.kind!=='battle_net');result.process_inventory=[{kind:'battle_net',pid:launcher.pid,start_ticks:launcher.start_ticks,session_id:1,executable:launcher.executable,visible_nonminimized_windows:0}];}return result;};const r=await h.runner.run();assert.equal(r.status,'completed');assert.equal(h.requests.filter(q=>q.op==='launch_battlenet').length,1);assert.ok(polls>=4);});
test('every dangerous canonical English/account token stops before launcher command or fallback input',async()=>{for(const text of ['Password','Verification','Agreement','Download','Authenticator','Update','Install','账号','帐号','安全令牌']){const h=harness({noWow:true});const original=h.ports.call;h.ports.call=async(...args)=>{const result=await original(...args);if(result.status==='observed')result.ocr!.items.push({text,x:200,y:500,width:150,height:30});return result;};const r=await h.runner.run();assert.equal(r.status,'blocked',text);assert.equal(h.requests.filter(q=>q.op==='input'||q.op==='launch_wow').length,0,text);}});
test('native user-required, unknown and permission refusals never trigger the technical CLI fallback',async()=>{for(const reason of ['launcher_requires_user:Agreement','launcher_requires_user:Password','blocked_auth','blocked_terms','blocked_update','unknown','permission_refused']){const h=harness({noWow:true});const original=h.ports.call;h.ports.call=async(...args)=>{const result=await original(...args);return args[0].op==='launch_wow'?{schema_version:1,status:'blocked',session_id:1,reason}:result;};const r=await h.runner.run();assert.equal(r.status,'blocked',reason);assert.equal(h.requests.filter(q=>q.op==='input').length,0,reason);}});
test('all canonical dangerous words are loaded from the same schema used by the Windows bridge',async()=>{const {recoveryStopTokens}=await import('../src/recovery/recognition.js');for(const words of Object.values(recoveryStopTokens))for(const text of words){const h=harness({noWow:true});const original=h.ports.call;h.ports.call=async(...args)=>{const result=await original(...args);if(result.status==='observed')result.ocr!.items.push({text,x:200,y:500,width:150,height:30});return result;};const r=await h.runner.run();assert.equal(r.status,'blocked',text);assert.equal(h.requests.filter(q=>q.op==='input'||q.op==='launch_wow').length,0,text);}});
test('cancellation during queued input audit prevents the dispatcher from invoking the input port',async()=>{const h=harness(),controller=new AbortController(),original=h.ports.append;h.ports.append=async event=>{await original(event);if(event.kind==='bridge_request'&&(event.data as {request:BridgeRequest}).request.op==='input')controller.abort('cancel_at_audit_boundary');};const r=await h.runner.run(controller.signal);assert.equal(r.status,'cancelled');assert.equal(h.requests.filter(q=>q.op==='input').length,0);assert.equal(r.input_issued,0);});
test('source freeze records transitive TS, authoritative schemas and local calibration without running a bridge',async()=>{const {freezeRecoverySources}=await import('../src/recovery/evidence.js'),{mkdtemp,readFile,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),{fileURLToPath}=await import('node:url');const directory=await mkdtemp(join(tmpdir(),'recovery-source-freeze-'));try{const manifest=await freezeRecoverySources(fileURLToPath(new URL('../..',import.meta.url)),directory,{mode:'offline'});assert.equal(manifest.models_enabled,false);assert.ok(manifest.files['protocol/session-recovery-v1.schema.json']);assert.ok(manifest.files['agent/src/benchmark/trace.ts']);assert.ok(manifest.files['tools/recover.py']);assert.ok(manifest.files['tools/recovery-calibration/selected-alliance-warrior.json']);assert.equal(JSON.parse(await readFile(join(directory,'manifest.json'),'utf8')).source_sha256,manifest.source_sha256);}finally{await rm(directory,{recursive:true,force:true});}});
test('after verified Enter World, two no-OCR unknown frames only wait until independently observed world',async()=>{const h=harness({scene:'character_select'}),original=h.ports.call,review=h.ports.review!;const pendingIds=new Set<string>();let observations=0;h.ports.call=async(...args)=>{const r=await original(...args);if(r.status==='observed'&&++observations>=2&&observations<=3){r.ocr!.items=[];pendingIds.add(r.observation_id!);}return r;};h.ports.review=async(frame,signal)=>pendingIds.has(frame.source.observation_id)?undefined:review(frame,signal);const runner=new RecoveryOrchestrator({runId:'empty-loading',directory:'/tmp/empty-loading',command:'launch',mode:'offline',authorized:true,targetCharacter:'小啊'},h.ports);const r=await runner.run();assert.equal(r.status,'completed');assert.equal(r.input_issued,1);assert.equal(r.effects_confirmed,1);assert.equal(r.events.filter(e=>e.kind==='pending_unknown_state').length,2);assert.equal(h.requests.filter(q=>q.op==='input').length,1);});
test('dangerous token during empty post-enter waiting stops immediately with no further input',async()=>{const h=harness({scene:'character_select'}),original=h.ports.call,review=h.ports.review!;const pendingIds=new Set<string>();let observations=0;h.ports.call=async(...args)=>{const r=await original(...args);if(r.status==='observed'){observations++;if(observations===2){r.ocr!.items=[];pendingIds.add(r.observation_id!);}if(observations===3)r.ocr!.items=[{text:'Verification',x:100,y:200,width:200,height:30}];}return r;};h.ports.review=async(frame,signal)=>pendingIds.has(frame.source.observation_id)?undefined:review(frame,signal);const r=await h.runner.run();assert.equal(r.status,'blocked');assert.match(r.reason,/authentication_required/);assert.equal(r.input_issued,1);assert.equal(r.effects_confirmed,0);assert.equal(h.requests.filter(q=>q.op==='input').length,1);});
test('first unknown already-running WoW is never presumed loading or allowed input',async()=>{const h=harness({noReview:true}),original=h.ports.call;h.ports.call=async(...args)=>{const r=await original(...args);if(r.status==='observed')r.ocr!.items=[];return r;};const r=await h.runner.run();assert.equal(r.status,'blocked');assert.equal(r.events.filter(e=>e.kind==='pending_unknown_state').length,0);assert.equal(h.requests.filter(q=>q.op==='input').length,0);});
