import test from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {canonical,hash} from '../src/behavior/validation.js';
import {compileBodyAction} from '../src/actions/compiler.js';
import {BodyRuntime,type BodyHand} from '../src/actions/runtime.js';
import type {NativeReceipt,NativeAction} from '../src/hand/protocol.js';
import {parseBodyProfile} from '../src/actions/profile.js';
import {bodyProfile,bodySample} from './fixtures/actions-body.js';
import {TraceRecorder} from '../src/benchmark/trace.js';
import type {LocalAssertion,LocalAssertionRecord,LocalQuery,LocalQueryResult,TutorialPlan} from '../src/tutorial/types.js';
import {LocalAssertionsClient,validateLocalRecord,validateLocalResult} from '../src/tutorial/local-data.js';
import {FIRST_TUTORIAL_INSTRUCTION,FIRST_TUTORIAL_NPC,compileSimulatedTutorialPlan,compileTutorialPlan,validateTutorialPlan} from '../src/tutorial/plan.js';
import {runTutorial} from '../src/tutorial/runtime.js';
import {compareTutorialDecision} from '../src/tutorial/benchmark.js';
import {recognizeTutorial,tutorialFields,tutorialLocalFact,tutorialQuestTracker} from '../src/tutorial/recognition.js';
import type {RecoveryFrame} from '../src/recovery/types.js';
import type {JsonValue,ObservedField} from '../src/core/protocol.js';
const repo=fileURLToPath(new URL('../..',import.meta.url));
const sourceClock={domain:'windows_qpc',clock_id:'test-windows-boot-1',ticks:100,unit:'ms' as const};
const session={session_id:1 as const,pid:99,start_ticks:'639268827443062278',hwnd:'0xabc',class:'waApplication Window',executable:'C:\\Games\\_retail_\\Wow.exe'};
const version={branch:'retail' as const,expansion:'midnight',patch:'12.1.0',build:69933,region:'cn' as const,locale:'zh_CN'};
function localFixture(){
  const assertion:LocalAssertion={schema_version:1,world_pack_sha256:'a'.repeat(64),world_sqlite_sha256:'b'.repeat(64),client_version:version,actor_id:'session-scoped-character',session,fact:{local_key:'exiles-reach.talk-jaina',kind:'tutorial_step',predicate:'interaction_instruction',state:'known',value:{npc_name:FIRST_TUTORIAL_NPC,instruction:FIRST_TUTORIAL_INSTRUCTION,target_signature:`visible-name:${FIRST_TUTORIAL_NPC}`}},observation_id:'original-readonly',source_event:{run_id:'explicit-fixture',seq:1,event_sha256:'c'.repeat(64)},source_clock:sourceClock,observed_at:'2026-10-06T00:00:01Z',capture_sha256:'d'.repeat(64),calibration_sha256:'e'.repeat(64),producer:'calibrated_cv',rule_version:'local-field-evidence-v1'};
  const record:LocalAssertionRecord={...assertion,assertion_sha256:hash(assertion),assertion_canonical:canonical(assertion)};
  const query:LocalQuery={world_pack_sha256:assertion.world_pack_sha256,client_version:version,actor_id:assertion.actor_id,session,local_key:assertion.fact.local_key,predicate:'interaction_instruction',as_of_clock:{...sourceClock,ticks:110},maximum_age:20};
  const result:LocalQueryResult={state:'known',value:record.fact.value,reason:'observed',record,records:[record],automatic_action_eligible:false};
  return{assertion,record,query,result,plan:compileSimulatedTutorialPlan(query,result,'b'.repeat(64))};
}
function screenSample(id:string,time:number,mode:'live'|'simulated'='simulated'){
  const sample=bodySample(id,time,mode);sample.observation.observation_seq=Number(id.replace(/[^0-9]/g,''))||1;
  const put=(key:string,value:JsonValue,source:ObservedField['source']=mode==='live'?'cv':'simulated')=>{sample.observation.fields[key]={status:'known',value,source,captured_at_ms:time,source_observation_id:id};};
  const signature=`visible-name:${FIRST_TUTORIAL_NPC}`;
  put('target.signature',signature);put('tutorial.instruction',FIRST_TUTORIAL_INSTRUCTION);put('dialog.open',false);put('dialog.absence_coverage_complete',true);
  put('target.screen_interaction',{id:'npc-point',signature,layout_id:'fixture-layout',x:500,y:300,enabled:true});put('input.cursor_free',true,mode==='live'?'window':'simulated');put('input.mouse_buttons_held',false,mode==='live'?'window':'simulated');
  return sample;
}
function screenProfile(){const p=bodyProfile();return parseBodyProfile({...p,capabilities:[...p.capabilities,'screen_interact']});}
function simulated(options:{effect?:boolean;absence?:boolean;staleEffect?:boolean;release?:boolean;cancel?:boolean}={}){
  const {plan}=localFixture();let time=1000,seq=0,acted=false;const logs:Array<{kind:string;data:unknown}>=[];const controller=new AbortController();
  const trace=new TraceRecorder({traceId:'tutorial-fixture',clock:()=>({domain:'simulation-monotonic',id:'run',ms:time}),timingKind:'virtual'});
  const ports={plan,profile:screenProfile(),runId:'run',hand:null,mode:'simulated' as const,finiteInputAuthorized:false,signal:controller.signal,now:()=>time,currentSourceClock:()=>({...sourceClock,ticks:110}),maximumLocalAge:20,currentIdentity:()=>({task_id:plan.task.id,task_revision:1,run_epoch:1}),trace,
    collect:async()=>{const s=screenSample(`o${++seq}`,++time);if(options.absence===false)delete s.observation.fields['dialog.absence_coverage_complete'];if(acted&&options.effect!==false){s.observation.fields['dialog.open']={...s.observation.fields['dialog.open']!,status:'known',value:true,...(options.staleEffect?{captured_at_ms:time-200}:{})};s.observation.fields['dialog.target_signature']={...s.observation.fields['target.signature']!};}return s;},
    sleep:async(ms:number)=>{acted=true;time+=ms;if(options.cancel)controller.abort('cancel');},append:async(kind:string,data:unknown)=>{logs.push({kind,data});}};
  return{ports,logs,trace};
}
test('local instruction compiles exactly one L4 sequence talk_to, no fake quest ID or next task',()=>{const {plan}=localFixture();validateTutorialPlan(plan);assert.equal(plan.task.behaviors[0]!.kind,'talk_to');assert.deepEqual(plan.task.params,{});assert.equal(plan.executable,false);assert.equal(plan.automatic_action_eligible,false);assert.equal(plan.evidence_scope,'simulated_fixture');assert.equal(JSON.stringify(plan).includes('quest_id'),false);});
test('local assertion wire/schema/canonical SHA and scope must match the original',()=>{const {record,query,result}=localFixture();validateLocalRecord(record);for(const changed of [{...record,actor_id:'different'},{...record,fact:{...record.fact,value:'changed'}},{...record,source_event:{...record.source_event,seq:2}}])assert.throws(()=>validateLocalRecord(changed),/hash/);for(const q of [{...query,actor_id:'other'},{...query,session:{...session,pid:100}},{...query,client_version:{...version,build:69934}},{...query,world_pack_sha256:'f'.repeat(64)},{...query,as_of_clock:{...sourceClock,clock_id:'different'}},{...query,as_of_clock:{...sourceClock,unit:'ticks' as const}},{...query,as_of_clock:{...sourceClock,ticks:99}},{...query,as_of_clock:{...sourceClock,ticks:130}}])assert.throws(()=>validateLocalResult(result,q),/binding|clock|freshness/);});
test('Python runtime extension crosses the real read-only Python→TS bridge; source tampering rejects',async()=>{
  const dir=await mkdtemp(join(tmpdir(),'tutorial-local-bridge-'));
  try{const python=join(repo,'.venv/bin/python');const setup=spawnSync(python,['-c',"from pathlib import Path\nfrom tests.test_local_assertions import fixture,query\nfrom game_database.local_assertions import LocalAssertions\nfrom game_database.store import canonical\nimport sys\nr,a,e,c=fixture(Path(sys.argv[1])); LocalAssertions(r,create=True).put(a); print(canonical(query(a))); r.close()",dir],{cwd:repo,encoding:'utf8'});assert.equal(setup.status,0,setup.stderr);const query=JSON.parse(setup.stdout) as LocalQuery;const client=new LocalAssertionsClient({repository:repo,database:join(dir,'agent.sqlite'),python});const result=await client.query(query);assert.equal(result.state,'known');const plan=await compileTutorialPlan(client,query,'b'.repeat(64));assert.equal(plan.evidence_scope,'live_runtime_local_assertion');
    await assert.rejects(compileTutorialPlan(client,{...query,session:{...query.session,pid:100}},'b'.repeat(64)),/blocked/);await assert.rejects(compileTutorialPlan(client,query,'f'.repeat(64)),/scope/);
    const change=spawnSync(python,['-c',"from pathlib import Path\nimport sys\nPath(sys.argv[1]).write_bytes(b'tampered original capture')",join(dir,'capture.bin')],{cwd:repo,encoding:'utf8'});assert.equal(change.status,0);await assert.rejects(client.query(query),/query_failed/);
  }finally{await rm(dir,{recursive:true,force:true});}
});
test('screen interaction uses a world target and free cursor, never pretends it is a UI click',()=>{const s=screenSample('o1',100),p=screenProfile(),action={kind:'screen_interact' as const,target_signature:`visible-name:${FIRST_TUTORIAL_NPC}`,element_id:'npc-point',x:500,y:300,duration_ms:60};const out=compileBodyAction(action,p,s.observation);assert.equal(out.status,'ready');if(out.status!=='ready'||!out.action)throw new Error('fixture');assert.ok(out.action.events.some(e=>e.kind==='button_down'&&e.button==='right'));assert.equal(s.observation.fields['input.mouse_mode']!.value,'world');for(const change of [{...action,x:501},{...action,target_signature:'other'},{...action,duration_ms:151}])assert.equal(compileBodyAction(change,p,s.observation).status,'blocked');s.observation.fields['input.cursor_free']!.value=false;assert.equal(compileBodyAction(action,p,s.observation).status,'blocked');});
test('full L4→L3→Body→gate simulated tutorial runs one action, distinguishes scenario effect',async()=>{const h=simulated();const result=await runTutorial(h.ports);assert.equal(result.result.status,'completed',result.result.reason);assert.equal(result.result.real_inputs,0);assert.equal(result.result.game_effect,'unverified');assert.equal(result.result.scenario_effect,'confirmed');assert.equal(result.next_task_started,false);assert.deepEqual(result.model_calls,{jev:0,brain:0,visual:0});for(const kind of ['task_start','behavior_selection_request','behavior_start','behavior_action_intent','layer_command_link','body_action_intent','body_action_outcome','behavior_result','task_result'])assert.ok(h.logs.some(e=>e.kind===kind),kind);assert.equal(h.logs.filter(e=>e.kind==='body_action_intent').length,1);assert.ok(h.trace.records().some(r=>r.kind==='span'&&r.stage==='code'&&r.meta.phase==='L4_task'));assert.ok(h.trace.records().some(r=>r.kind==='span'&&r.stage==='code'&&r.meta.phase==='L3_behavior'));});
test('NPC+hint presence cannot create dialog absence or authorize input',async()=>{const h=simulated({absence:false});const result=await runTutorial(h.ports);assert.equal(result.result.status,'blocked');assert.match(result.result.reason,/absence_coverage/);assert.equal(h.logs.filter(e=>e.kind==='body_action_intent').length,0);});
test('input end without independent dialog effect is never task success and cannot retry',async()=>{for(const extra of [{effect:false},{staleEffect:true}]){const h=simulated(extra);const result=await runTutorial(h.ports);assert.notEqual(result.result.status,'completed');assert.equal(result.result.game_effect,'unverified');assert.equal(h.logs.filter(e=>e.kind==='body_action_intent').length,1);}});
test('cancellation propagates through L4/L3 and Body without another action',async()=>{const h=simulated({cancel:true});const result=await runTutorial(h.ports);assert.equal(result.result.status,'cancelled');assert.equal(h.logs.filter(e=>e.kind==='body_action_intent').length,1);assert.equal(result.next_task_started,false);});
test('stale local source, unmapped clock and changed task identity reject before L4',async()=>{for(const extra of [{currentSourceClock:()=>({...sourceClock,ticks:200})},{currentSourceClock:()=>({...sourceClock,clock_id:'other'})},{currentIdentity:()=>({task_id:'wrong',task_revision:1,run_epoch:1})}]){const h=simulated();await assert.rejects(runTutorial({...h.ports,...extra}),/stale|unmapped|identity/);assert.equal(h.logs.length,0);}});
test('simulated local plan never becomes live input through a mode rename',async()=>{const h=simulated();await assert.rejects(runTutorial({...h.ports,mode:'live',finiteInputAuthorized:true}),/simulated_plan/);assert.equal(h.logs.length,0);});
function recoveryFrame():RecoveryFrame{
  const id='o1';return{requested_at_ms:100,received_at_ms:110,source:{observation_id:id,capture_sha256:'d'.repeat(64),width:1000,height:800,observation_path:'/tmp/explicit-fixture'},observation:{schema_version:1,status:'observed',session_id:1,observation_id:id,target:session,window:{client_width:1000,client_height:800,dpi:96,focused:true,visible:true,minimized:false,recovery_safety:{allowed:true,visible:true,minimized:false,focused:true,client_fully_visible:true,user_idle_ms:6000,idle_threshold_ms:5000,occluders:[]}},capture:{file:'client.png',sha256:'d'.repeat(64),width:1000,height:800,started_windows_qpc_ms:10000,finished_windows_qpc_ms:10001,method:'printwindow'},tutorial_cv:{verified:true,source:'calibrated_cv',kind:'talk_jaina',npc_name:FIRST_TUTORIAL_NPC,calibration_sha256:'e'.repeat(64),reference_sha256:'f'.repeat(64),regions:[{region:'name',matched:true,mask_iou:.99,min_iou:.9},{region:'instruction',matched:true,mask_iou:.98,min_iou:.9}],action_point:{x:500,y:300},safe_focus_point:{x:800,y:700},observation_id:id,capture_sha256:'d'.repeat(64)},ocr:{status:'available',items:[],raw_text_retained:false},started_windows_qpc_ms:9999,finished_windows_qpc_ms:10002}};
}
test('same-source tutorial CV yields only visible signature/point/instruction and leaves dialog unknown',()=>{const frame=recoveryFrame(),r=recognizeTutorial(frame);assert.equal(r.instruction_present,true);assert.equal(r.dialog,'unknown');assert.equal(tutorialLocalFact(r).state,'known');const c=bodySample('o1',100,'live');c.artifact!.sha256='d'.repeat(64);c.bracket.sample.artifact!.sha256='d'.repeat(64);c.bracket.received_at_ms=110;c.observation.at_ms=110;const fields=tutorialFields(c,frame);assert.equal(fields['dialog.open'],undefined);assert.equal(fields['input.cursor_free'],undefined);assert.equal(fields['quest.1.accepted'],undefined);assert.equal(fields['target.signature']!.source,'cv');frame.observation.tutorial_cv!.capture_sha256='a'.repeat(64);assert.throws(()=>recognizeTutorial(frame),/source_binding/);});
test('a separate left NPC header and associated dialog control can confirm an OCR dialog; generic Accept cannot',()=>{const f=recoveryFrame();delete f.observation.tutorial_cv;f.observation.ocr.items=[{text:'接受',x:100,y:600,width:60,height:30}];assert.equal(recognizeTutorial(f).dialog,'unknown');f.observation.ocr.items.push({text:FIRST_TUTORIAL_NPC,x:100,y:100,width:200,height:30});assert.equal(recognizeTutorial(f).dialog,'open');f.observation.ocr.items[1]!.x=600;assert.equal(recognizeTutorial(f).dialog,'unknown');});
test('fragmented native header and task controls identify the same current NPC panel',()=>{
  const f=recoveryFrame();delete f.observation.tutorial_cv;
  f.observation.ocr.items=[{text:'吉安娜',x:100,y:100,width:200,height:30},{text:'·',x:100,y:100,width:200,height:30},{text:'普罗德摩尔',x:100,y:100,width:200,height:30},{text:'拒绝',x:180,y:600,width:60,height:30}];
  assert.equal(recognizeTutorial(f).dialog,'open');f.observation.ocr.items[2]!.y=160;assert.equal(recognizeTutorial(f).dialog,'unknown');
});
test('tracker detection requires the current right-side title and objective, not chat or generic task text',()=>{
  const source={kind:'file_screenshot' as const,observation_id:'o',capture_sha256:'a'.repeat(64),width:1000,height:800,source_qpc_ms:1};
  const items=[{text:'热身',x:800,y:250,width:60,height:20},{text:'0/1 摧毁作战假人',x:800,y:280,width:150,height:20}];
  assert.equal(tutorialQuestTracker(source,items).length,1);assert.equal(tutorialQuestTracker(source,[items[0]!]).length,0);assert.equal(tutorialQuestTracker(source,items.map(i=>({...i,x:10}))).length,0);
});
test('same-frame OCR adoption retains its source and never masquerades as CV',()=>{const f=recoveryFrame();delete f.observation.tutorial_cv;f.observation.ocr.items=[{text:FIRST_TUTORIAL_NPC,x:100,y:100,width:200,height:30},{text:'接受',x:100,y:600,width:60,height:30}];const c=bodySample('o1',100,'live');c.artifact!.sha256='d'.repeat(64);c.bracket.sample.artifact!.sha256='d'.repeat(64);c.bracket.received_at_ms=110;c.observation.at_ms=110;const fields=tutorialFields(c,f);assert.equal(fields['dialog.open']!.value,true);assert.equal(fields['dialog.open']!.source,'local_ocr');assert.equal(fields['target.screen_interaction'],undefined);c.observation.id='another-source';assert.throws(()=>tutorialFields(c,f),/source_binding/);});
test('readonly single-layer decision uses visual+brain while layered uses current unique code candidate, no execute port',async()=>{const {plan}=localFixture();const obs=screenSample('o1',100,'live').observation;let time=100,visual=0,brain=0;const result=await compareTutorialDecision(plan,obs,{now:()=>time,observe:async()=>obs,append:async()=>{},measure:async(_s,_r,work)=>work(),visual:async(o)=>{visual++;time+=20;return{summary:'同一教程目标和NPC候选',based_on_observation_id:o.id,captured_at_ms:100,source:'seed'};},choose:async(role,request)=>{assert.equal(role,'brain');brain++;time+=30;const r=request as import('../src/brain/execution/types.js').BrainRequest;return{request_id:r.id,plan_revision:r.plan.revision,evidence_observation_id:r.based_on_observation_id,consulted_fact_ids:r.consulted_fact_ids,route_id:'talk-to-visible-npc',reason:'选择唯一当前交谈候选'};}},new AbortController().signal);assert.equal(result.input_issued,0);assert.equal(result.layered.selection.route,'code');assert.equal(result.layered.selection.status,'selected');assert.equal(result.single.selection.status,'selected',result.single.selection.reason);assert.equal(visual,1);assert.equal(brain,1);assert.equal(result.paired_input_benchmark,false);});
test('live Body rejects manual/CV cursor laundering and preserves ordinary artifact gate',async()=>{
  const signature=`visible-name:${FIRST_TUTORIAL_NPC}`,action={kind:'screen_interact' as const,target_signature:signature,element_id:'npc-point',x:500,y:300,duration_ms:60};
  for(const source of ['cv','manual','seed'] as const){let time=100;const s=screenSample('o1',time,'live');s.observation.fields['input.cursor_free']!.source=source;const runtime=new BodyRuntime({profile:screenProfile(),runId:'run',hand:null,collect:async()=>s,now:()=>time,currentIdentity:()=>({task_id:'task',task_revision:1,run_epoch:1})});const r=await runtime.execute(action,{command_id:`cmd-${source}`,task_id:'task',task_revision:1,run_epoch:1,mode:'live',conditions:[],signal:new AbortController().signal});assert.equal(r.status,'blocked');assert.equal(r.real_inputs,0);}
});
test('real Python→TS reads recheck mutated row, source run, actor and original fact records',async()=>{
  const dir=await mkdtemp(join(tmpdir(),'tutorial-negative-bridge-'));
  try{
    const python=join(repo,'.venv/bin/python');
    for(const mutation of ['row','run','actor','event']){
      const child=join(dir,mutation);const setup=spawnSync(python,['-c',"from pathlib import Path\nfrom tests.test_local_assertions import fixture,query\nfrom game_database.local_assertions import LocalAssertions\nfrom game_database.store import canonical,canonical_sha256\nfrom tests.test_game_runtime import run_record\nimport sys\np=Path(sys.argv[1]);p.mkdir();r,a,e,c=fixture(p); LocalAssertions(r,create=True).put(a);print(canonical(query(a)))\nm=sys.argv[2]\nif m=='row':\n r.connection.execute('DROP TRIGGER local_assertion_no_update');r.connection.execute('UPDATE local_assertion SET sha256=?',('c'*64,))\nelif m=='run':\n v=run_record(mode='simulated');r.connection.execute('UPDATE run SET mode=?,content_sha256=?,payload=? WHERE run_id=?',('simulated',canonical_sha256(v),canonical(v),'run-1'))\nelif m=='actor':\n r.connection.execute(\"UPDATE character SET namespace='classic-era' WHERE character_id='character-1'\")\nelse:\n e.pop('event_sha256');e['payload']['local_assertions']=[];r.connection.execute('UPDATE event_index SET event_sha256=?,payload=? WHERE run_id=? AND seq=1',(canonical_sha256(e),canonical(e),'run-1'))\nr.close()",child,mutation],{cwd:repo,encoding:'utf8'});assert.equal(setup.status,0,setup.stderr);const q=JSON.parse(setup.stdout) as LocalQuery;await assert.rejects(new LocalAssertionsClient({repository:repo,database:join(child,'agent.sqlite'),python}).query(q),/query_failed/,mutation);
    }
  }finally{await rm(dir,{recursive:true,force:true});}
});
test('freshness/scope isolation is retained over the real Python→TS process boundary',async()=>{
  const dir=await mkdtemp(join(tmpdir(),'tutorial-scope-bridge-'));
  try{const python=join(repo,'.venv/bin/python'),setup=spawnSync(python,['-c',"from pathlib import Path\nfrom tests.test_local_assertions import fixture,query\nfrom game_database.local_assertions import LocalAssertions\nfrom game_database.store import canonical\nimport sys\nr,a,e,c=fixture(Path(sys.argv[1]));LocalAssertions(r,create=True).put(a);print(canonical(query(a)));r.close()",dir],{cwd:repo,encoding:'utf8'});assert.equal(setup.status,0,setup.stderr);const q=JSON.parse(setup.stdout) as LocalQuery,client=new LocalAssertionsClient({repository:repo,database:join(dir,'agent.sqlite'),python});for(const extra of [{actor_id:'other'},{session:{...q.session,pid:100}},{session:{...q.session,hwnd:'0xabd'}},{world_pack_sha256:'f'.repeat(64)},{client_version:{...q.client_version,build:69934}},{as_of_clock:{...q.as_of_clock,ticks:99}},{as_of_clock:{...q.as_of_clock,ticks:200}},{as_of_clock:{...q.as_of_clock,domain:'coordinator_monotonic'}},{as_of_clock:{...q.as_of_clock,clock_id:'other'}},{as_of_clock:{...q.as_of_clock,unit:'ms' as const}}])assert.equal((await client.query({...q,...extra})).state,'unknown');
  }finally{await rm(dir,{recursive:true,force:true});}
});
test('live Body policy probe binds retained source after its gate, protects clones, marks input separately from effect',async()=>{
  let time=100,seq=0,binds=0;const sent:NativeAction[]=[];
  const window={token:'target-token',hwnd:'0xabc',pid:99,client_width:1000,client_height:800,focused:true};
  const receipt=(id:string,op:NativeReceipt['op']='execute',count=3):NativeReceipt=>({protocol:'wow-input',version:1,type:'receipt',session_id:'explicit-unit-hand',id,op,status:op==='execute'?'completed':'ok',input:{status:count?'released':'not_sent',events_requested:count,events_inserted:count,released:true},effect:{status:'unknown'},timing:{clock:'windows_qpc',started_ms:900100,finished_ms:900160},input_timing:{clock:'windows_qpc',first_send_started_ms:900101,first_send_finished_ms:900102,last_send_finished_ms:900160},local_clock:{domain:'windows-qpc',at_ms:900161}});
  const hand:BodyHand={sessionId:'explicit-unit-hand',ready:{protocol:'wow-input',version:1,type:'ready',session_id:'explicit-unit-hand',executor_pid:1,watchdog_pid:2,window,capabilities:{timeline:true,keys:[],max_duration_ms:5000,heartbeat_lease_ms:1000},local_clock:{domain:'windows-qpc',at_ms:900000}},execute:async(action,options)=>{sent.push(structuredClone(action));time+=60;return receipt(options!.id!);},cancel:async()=>receipt('cancel','cancel',0),releaseAll:async()=>receipt('release','release_all',0)};
  const trace=new TraceRecorder({traceId:'explicit-policy-probe',clock:()=>({domain:'coordinator-monotonic',id:'test-coordinator',ms:time})});
  const runtime=new BodyRuntime({profile:screenProfile(),runId:'run',hand,now:()=>time,trace,windowsClockId:'test-windows',expectedWindow:window,currentIdentity:()=>({task_id:'task',task_revision:1,run_epoch:1}),collect:async()=>screenSample(`o${++seq}`,time++,'live'),bindSource:async(before,intent)=>{binds++;before.observation.fields['target.signature']!.value='tampered clone';if(intent.action.name==='native_input'&&intent.action.args.kind==='timeline')intent.action.args.events=[];}});
  const result=await runtime.execute({kind:'screen_interact',target_signature:`visible-name:${FIRST_TUTORIAL_NPC}`,element_id:'npc-point',x:500,y:300,duration_ms:60},{command_id:'source-bound',task_id:'task',task_revision:1,run_epoch:1,mode:'live',conditions:[],signal:new AbortController().signal});
  assert.equal(result.status,'completed',result.reason??'');assert.equal(result.real_inputs,1);assert.equal(result.game_effect,'unverified');assert.equal(binds,1);assert.equal(sent.length,1);if(sent[0]?.kind==='timeline')assert.equal(sent[0].events.length,3);assert.equal(trace.records().filter(r=>r.kind==='mark'&&r.phase==='input_issued').length,1);assert.equal(trace.records().filter(r=>r.kind==='mark'&&r.phase==='effect_confirmed').length,0);
});
test('same-source screenshot substitution and wrong OCR geometry never become tutorial fields',()=>{
  const frame=recoveryFrame(),c=bodySample('o1',100,'live');c.bracket.received_at_ms=110;c.observation.at_ms=110;assert.throws(()=>tutorialFields(c,frame),/source_binding/);
  delete frame.observation.tutorial_cv;frame.observation.ocr.items=[{text:FIRST_TUTORIAL_NPC,x:100,y:100,width:200,height:30},{text:'接受',x:800,y:600,width:60,height:30}];assert.equal(recognizeTutorial(frame).dialog,'unknown');
});
test('independent low-frequency effect collection starts after Body returns and retains its older capture time',async()=>{
  const h=simulated({effect:false});let effectCollections=0,captureTime=0;
  const result=await runTutorial({...h.ports,collectEffect:async()=>{effectCollections++;const c=await h.ports.collect();captureTime=c.bracket.started_at_ms;c.observation.fields['dialog.open']={...c.observation.fields['dialog.open']!,status:'known',value:true};c.observation.fields['dialog.target_signature']={...c.observation.fields['target.signature']!};await h.ports.sleep(900);c.observation.at_ms=h.ports.now();c.bracket.received_at_ms=h.ports.now();return c;}});
  assert.equal(result.result.status,'completed',result.result.reason);assert.equal(effectCollections,1);const body=h.logs.find(e=>e.kind==='body_action_outcome')!.data as {outcome:{finished_at_ms:number}};assert.ok(captureTime>=body.outcome.finished_at_ms);assert.ok(h.trace.records().some(r=>r.kind==='span'&&r.stage==='effect'&&r.meta.phase==='L3_independent_effect_collection'&&r.end.ms-r.start.ms>=900));assert.equal(result.result.real_inputs,0);
});
test('longer effect freshness allowance does not relax the Body input gate',async()=>{
  const h=simulated(),collect=h.ports.collect;h.ports.collect=async()=>{const c=await collect();c.observation.fields['target.signature']!.captured_at_ms-=800;return c;};const result=await runTutorial(h.ports);assert.equal(result.result.status,'blocked');assert.match(result.result.reason,/stale|no_valid_behavior_candidate/);assert.equal(h.logs.filter(e=>e.kind==='body_action_intent').length,0);
});
