import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {join,resolve} from 'node:path';
import {readFile,mkdir,writeFile,rm} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';
import {memorySample,MemoryOwner} from './fixtures/resident-memory.js';
import {MemoryFrameRegistry} from '../src/eye/memory-frame.js';
import {ResidentTutorialCollector} from '../src/tutorial/resident-adapter.js';
import {memorySource} from '../src/tutorial/tagged-evidence.js';
import {recognizeResidentTutorial} from '../src/tutorial/recognition.js';
import {finishTutorialResident,validateTutorialFieldConfig} from '../src/tutorial/field-entry.js';
import {verifyResidentClientProof,type TutorialClientProof} from '../src/tutorial/client-proof.js';
import {readonlyTutorialModels} from '../src/tutorial/field-models.js';
import {tutorialLatency} from '../src/tutorial/metrics.js';
import {tutorialMain} from '../src/tutorial/cli.js';
import {TraceRecorder} from '../src/benchmark/trace.js';
import type {ResidentClient,ResidentCleanup} from '../src/resident/client.js';
import type {ResidentMemorySample,ResidentEvidence} from '../src/resident/protocol.js';
import type {NativeReceipt} from '../src/hand/protocol.js';
import {loadResidentValidator,assertResident} from '../src/resident/protocol.js';
import {compileTutorialPlan} from '../src/tutorial/plan.js';
import {LocalAssertionsClient} from '../src/tutorial/local-data.js';
import {runTutorial} from '../src/tutorial/runtime.js';
import {bodyBindingsSha256,parseBodyProfile} from '../src/actions/profile.js';
import type {LocalQuery} from '../src/tutorial/types.js';
import {parseColdRecovery,coldRecoveryAllowsTutorial,tutorialInputCounts} from '../src/tutorial/accounting.js';
import type {RecoveryResult} from '../src/recovery/types.js';
const repository=fileURLToPath(new URL('../..',import.meta.url)),cal='c'.repeat(64),absence='e'.repeat(64);
function sample(){const s=memorySample();s.memory_frame.target_scope='retail_wow';s.memory_frame.rois=[{id:'npc_name-0.555556',x:400,y:160,width:200,height:40,sha256:'a'.repeat(64),calibration_id:'tutorial',calibration_sha256:cal},{id:'tutorial_hint-0.555556',x:300,y:520,width:300,height:50,sha256:'b'.repeat(64),calibration_id:'tutorial',calibration_sha256:cal}];s.cv.tutorial_interaction={verified:true,source:'calibrated_cv',kind:'talk_jaina',npc_name:'吉安娜·普罗德摩尔',calibration_sha256:cal,reference_sha256:'f'.repeat(64),regions:[{region:'npc_name',matched:true,mask_iou:.99,min_iou:.9,live_rect:{x:410,y:170,width:180,height:30}},{region:'tutorial_hint',matched:true,mask_iou:.99,min_iou:.9,live_rect:{x:310,y:530,width:280,height:30}}],action_point:{x:500,y:300},safe_focus_point:{x:800,y:700}};return s;}
function fullEvidence(s:ResidentMemorySample):ResidentEvidence{return{protocol:'wow-resident',version:1,type:'evidence',session_id:s.session_id,id:'evidence',sample:s,artifact:{id:'actual-file-fixture',windows_path:'C:\\fixture.png',sha256:'d'.repeat(64),width:1000,height:800,source_frame_id:s.memory_frame.frame_id,source_qpc_ms:s.memory_frame.source_qpc_ms},ocr:null,local_clock:s.local_clock};}
function harness(s=sample()){
  const owner=new MemoryOwner();owner.receive(s);const bracket={sample:s,started_at_ms:100,received_at_ms:110};let at=110,evidenceCalls=0,sampleCalls=0;const emitter=new EventEmitter();
  const client=Object.assign(emitter,owner,{sample:async()=>{sampleCalls++;return bracket;},evidence:async()=>{evidenceCalls++;return{...fullEvidence(s),bracket};},validateBracket:owner.validateBracket.bind(owner),bindSource:async()=>{}}) as unknown as ResidentClient;
  const registry=new MemoryFrameRegistry(owner);const collector=new ResidentTutorialCollector({client,registry,runId:'run',now:()=>at,calibrationSha256:cal,absenceCalibrationSha256:absence,append:async()=>{},saveEvidence:async(e)=>({path:'/explicit-offline-fixture.png',sha256:e.artifact.sha256})});
  return{owner,registry,collector,client,s,bracket,advance:(ms:number)=>at+=ms,counts:()=>({sampleCalls,evidenceCalls})};
}
test('resident tutorial uses one tagged recognition core, ROI SHA never becomes full PNG SHA',()=>{const s=sample(),r=recognizeResidentTutorial(s,'current',cal);assert.equal(r.capture_sha256,null);assert.equal(r.source_proof.kind,'resident_memory_roi');assert.equal(r.dialog,'unknown');assert.equal(r.instruction_present,true);assert.equal(r.source_proof.source_qpc_ms,s.memory_frame.source_qpc_ms);});
test('fixture and missing native scope reject before tutorial recognition or model worker construction',async()=>{for(const scope of ['recording_fixture',undefined]){const s=sample();if(scope)(s.memory_frame as unknown as {target_scope?:string}).target_scope=scope;else delete(s.memory_frame as unknown as {target_scope?:string}).target_scope;assert.throws(()=>memorySource(s,'current'),/retail_wow/);const h=harness(s);await assert.rejects(h.collector.collect(),/retail_wow/);await assert.rejects(readonlyTutorialModels({repository,python:'must-not-be-started',imagePath:'/fixture.jpg',sourceObservation:{protocol:'wow-agent',version:1,type:'observation',id:'current',run_id:'run',observation_seq:1,window:null,at_ms:100,fields:{},artifacts:[]},sourceEvidence:fullEvidence(s),authorized:true,allowUpload:true,now:()=>100,append:async()=>{},trace:new TraceRecorder({traceId:'run',clock:()=>({domain:'coordinator-monotonic',id:'run',ms:100})})}),/retail_wow/);}});
test('hot collection performs no PNG evidence/OCR call and keeps native source clocks',async()=>{const h=harness(),c=await h.collector.collect(true);assert.deepEqual(h.counts(),{sampleCalls:1,evidenceCalls:0});assert.equal(c.artifact,null);assert.deepEqual(c.observation.artifacts,[]);assert.equal(c.observation.fields['target.signature']!.source_clock!.value_ms,900001);assert.equal(c.observation.fields['input.cursor_free']!.source_clock!.value_ms,900006);assert.equal(c.observation.fields['dialog.open']!.status,'unknown');assert.equal(h.registry.owns(c),true);});
test('native source ROI/calibration/region substitution is rejected before registration',async()=>{for(const change of [(s:ResidentMemorySample)=>{s.memory_frame.rois[0]!.calibration_sha256='f'.repeat(64);},(s:ResidentMemorySample)=>{(s.cv.tutorial_interaction.regions as Array<{live_rect:{x:number}}>)[0]!.live_rect.x=700;},(s:ResidentMemorySample)=>{s.cv.tutorial_interaction.calibration_sha256='f'.repeat(64);}]){const s=sample();change(s);const h=harness(s);await assert.rejects(h.collector.collect(),/calibration|native_proof/);}});
test('tutorial contract fixture validates against the actual Native unique schema, no real WGC frame claimed',async()=>{const v=await loadResidentValidator(join(repository,'protocol/resident-session-v1.schema.json'),join(repository,'protocol/native-input-v1.schema.json'));const s=sample();assertResident(s,v);assertResident(fullEvidence(s),v);for(const scope of ['missing','unknown']){const changed=structuredClone(s);if(scope==='missing')delete(changed.memory_frame as unknown as {target_scope?:string}).target_scope;else(changed.memory_frame as unknown as {target_scope:string}).target_scope=scope;assert.throws(()=>assertResident(changed,v),/schema/);}});
test('actual Native absence wire ID admits exact independent full coverage; old ID cannot',async()=>{for(const valid of [true,false]){const s=sample();s.cv.dialog_absence={status:'known',dialog_open:false,coverage_complete:true,calibration_sha256:absence,regions:[{id:'dialog_absence',matched:true,live_rect:{x:0,y:0,width:450,height:720}}]};s.memory_frame.rois.push({id:valid?'dialog-absence-dialog_absence':'dialog_absence',x:0,y:0,width:450,height:720,sha256:'e'.repeat(64),calibration_id:'tutorial-dialog-absence-exact-v1',calibration_sha256:absence});const h=harness(s);if(valid){const c=await h.collector.collect();assert.equal(c.observation.fields['dialog.open']!.value,false);assert.equal(c.observation.fields['dialog.absence_coverage_complete']!.value,true);}else await assert.rejects(h.collector.collect(),/full_coverage/);}});
test('only independent paired native OCR marks dialog open, low-frequency delay never refreshes source',async()=>{const h=harness(),e=fullEvidence(h.s);e.ocr={status:'available',raw_text_retained:false,items:[{text:'吉安娜·普罗德摩尔',x:100,y:100,width:200,height:30},{text:'接受',x:100,y:600,width:60,height:30}]};h.client.evidence=async()=>{h.advance(900);return{...e,bracket:h.bracket};};const c=await h.collector.collectEffect();assert.equal(c.observation.fields['dialog.open']!.value,true);assert.equal(c.observation.fields['dialog.open']!.source,'local_ocr');assert.equal(c.observation.fields['dialog.open']!.captured_at_ms,100);assert.equal(c.observation.at_ms,1010);assert.equal((c.observation.fields['dialog.paired_ocr_proof']!.value as {capture_sha256:string}).capture_sha256,e.artifact.sha256);assert.equal(h.registry.owns(c),true);});
test('OCR effect cannot pair a generic accept, wrong-frame full PNG or right-side header',async()=>{for(const change of ['generic','frame','right']){const h=harness(),e=fullEvidence(h.s);e.ocr={status:'available',raw_text_retained:false,items:[{text:'接受',x:100,y:600,width:60,height:30},...(change==='generic'?[]:[{text:'吉安娜·普罗德摩尔',x:change==='right'?600:100,y:100,width:200,height:30}])]};if(change==='frame')e.artifact.source_frame_id='old';h.client.evidence=async()=>({...e,bracket:h.bracket});if(change==='frame')await assert.rejects(h.collector.collectEffect(),/binding/);else assert.equal((await h.collector.collectEffect()).observation.fields['dialog.open']!.status,'unknown');}});
const native=(op:NativeReceipt['op']='release_all'):NativeReceipt=>({protocol:'wow-input',version:1,type:'receipt',session_id:'session',id:'release',op,status:'ok',input:{status:'released',events_requested:0,events_inserted:0,released:true},effect:{status:'unknown'},timing:{clock:'windows_qpc',started_ms:null,finished_ms:2},local_clock:{domain:'windows-qpc',at_ms:2}});
function cleanup():ResidentCleanup{return{stopped:{protocol:'wow-resident',version:1,type:'stopped',session_id:'session',id:'stopped',reason:'normal',release_confirmed:true,release_receipt:native(),ledger_empty:true,native_exited:true,capture_disposed:true,local_clock:{domain:'windows-qpc',at_ms:2}},task_deleted:true,task_absence_verified:true,launcher_exit_code:0,release_scope:'native_receipt_and_ledger'};}
test('terminal cleanup needs native release/ledger/exited/capture and independent task absence',async()=>{for(const mutation of ['none','no_stopped','receipt','ledger','exit','capture','deleted','absence','scope','wrong_session']){const c=cleanup();if(mutation==='no_stopped')c.stopped=null;else if(mutation==='receipt')c.stopped!.release_receipt=null;else if(mutation==='ledger')c.stopped!.ledger_empty=false;else if(mutation==='exit')c.stopped!.native_exited=false;else if(mutation==='capture')c.stopped!.capture_disposed=false;else if(mutation==='deleted')c.task_deleted=false;else if(mutation==='absence')c.task_absence_verified=false;else if(mutation==='scope')c.release_scope='unconfirmed';else if(mutation==='wrong_session')c.stopped!.release_receipt!.session_id='other';let released=0,closed=0;const result=await finishTutorialResident({ready:{} as ResidentClient['ready'],sessionId:'session',releaseAll:async()=>{released++;return native();},close:async()=>{closed++;return c;}});assert.equal(result.release,mutation==='none'?'confirmed':'unconfirmed');assert.equal(released,1);assert.equal(closed,1);}});
test('release exception still closes; readonly absence is distinct from physical release proof',async()=>{let closed=0;const c=cleanup();c.release_scope='no_executor_acquired';c.stopped!.release_receipt=null;c.stopped!.ledger_empty=null;c.stopped!.native_exited=null;const r=await finishTutorialResident({ready:null,sessionId:'session',releaseAll:async()=>{throw new Error('never');},close:async()=>{closed++;return c;}});assert.equal(r.scope,'readonly_no_executor_acquired');assert.equal(closed,1);const fail=await finishTutorialResident({ready:{} as ResidentClient['ready'],sessionId:'session',releaseAll:async()=>{throw new Error('pipe EOF');},close:async()=>{closed++;throw new Error('unavailable');}});assert.equal(fail.release,'unconfirmed');assert.equal(closed,2);});
function proof(s:ResidentMemorySample):TutorialClientProof{return{protocol:'wow-tutorial-client-probe',version:1,evidence_scope:'readonly_current_client',target:s.memory_frame.target,client_version:{branch:'retail',expansion:'midnight',patch:'12.1.0',build:69933,region:'cn',locale:'zh_CN'},metadata:{pid:99,proc:'Wow',exe:s.window.executable,start_ticks:s.window.start_ticks,file_version:'12.1.0.69933',branch:'retail',region:'CN',text_locale:'zhCN'},metadata_source:{path:'/actual-frozen-metadata.json',sha256:'a'.repeat(64),scope:'session0_readonly_process_file_metadata',captured_at:'2026-10-07T00:00:00Z'},window_source:{target_scope:'retail_wow',frame_id:s.memory_frame.frame_id,seq:s.seq,windows_clock_id:s.memory_frame.windows_clock_id,source_qpc_ms:s.memory_frame.source_qpc_ms,client_width:s.window.client_width,client_height:s.window.client_height,dpi:s.window.dpi},review:{reviewer:'root',reviewed_at:'2026-10-07T00:00:01Z',expansion_verified:true}};}
test('client probe preserves separate metadata UTC/native QPC and rejects six-dimensional or instance mismatch',()=>{const s=sample(),p=proof(s);verifyResidentClientProof(p,p.client_version,s);for(const mutate of [(p:TutorialClientProof)=>p.metadata.file_version='12.1.0.69934',(p:TutorialClientProof)=>p.metadata.text_locale='enUS',(p:TutorialClientProof)=>p.metadata.start_ticks='different',(p:TutorialClientProof)=>p.window_source.windows_clock_id='different',(p:TutorialClientProof)=>p.window_source.source_qpc_ms-=300001,(p:TutorialClientProof)=>p.client_version.expansion=null]){const q=structuredClone(p);mutate(q);assert.throws(()=>verifyResidentClientProof(q,p.client_version,s),/probe|dimensions/);}});
test('entry rejects unsupported targets, missing version facts and excess native action budget configuration',()=>{const s=sample(),p=proof(s),c={version:1,target:s.memory_frame.target,client_version:p.client_version,client_probe_path:'/probe.json',client_probe_sha256:cal,world_directory:'/world',world_pack_sha256:cal,world_sqlite_sha256:cal,runtime_database:'/agent.sqlite',calibration_path:'/calibration.json',calibration_sha256:cal,duration_ms:30000};validateTutorialFieldConfig(c);for(const change of [{duration_ms:300001},{client_version:{...p.client_version,build:null}},{target:{...s.memory_frame.target,windows_session_id:0}},{max_actions:8},{target_scope:'recording_fixture'}])assert.throws(()=>validateTutorialFieldConfig({...c,...change}));});
test('latency uses same-domain QPC source to issued; effect spans and coordinator baseline remain separate',()=>{const trace=new TraceRecorder({traceId:'trace',clock:()=>({domain:'coordinator-monotonic',id:'coordinator',ms:100})});trace.mark('observation','a',{}, {domain:'windows-qpc',id:'qpc',ms:10000});trace.mark('input_issued','a',{events_inserted:3},{domain:'windows-qpc',id:'qpc',ms:10080});trace.record({kind:'span',trace_id:'trace',action_id:null,timing_kind:'measured',stage:'brain',start:{domain:'coordinator-monotonic',id:'coordinator',ms:100},end:{domain:'coordinator-monotonic',id:'coordinator',ms:500},outcome:'ok',meta:{scope:'decision_only'}});trace.mark('effect_confirmed','a',{}, {domain:'coordinator-monotonic',id:'coordinator',ms:900});const m=tutorialLatency(trace.records());assert.equal(m.windows_observation_to_input_issued.p50_ms,80);assert.equal(m.stages['coordinator-monotonic/brain/decision_only']!.p50_ms,400);assert.equal(m.target_p50_less_than_150_ms,true);});
test('real Python field writer→local bridge→L4/L3/Body memory gate→contract hand has one linked input and independent effect',async()=>{
  const dir=await mkdtemp(join(tmpdir(),'tutorial-memory-chain-')),python=join(repository,'.venv/bin/python');
  try{
    const setup=spawnSync(python,['-B','-c',"from pathlib import Path\nimport sys\nfrom tests.test_tutorial_field import fixture\nfrom game_database.tutorial_field import register_snapshot\nfrom game_database.store import canonical\nr,s,p,w=fixture(Path(sys.argv[1]));got=register_snapshot(Path(sys.argv[1])/'agent.sqlite',r);print(canonical({'world_pack_sha256':r['run']['world_pack_sha256'],'client_version':r['run']['client_version'],'actor_id':got['actor_id'],'session':got['session'],'local_key':'exiles-reach.talk-jaina','predicate':'interaction_instruction','as_of_clock':got['source_clock'],'maximum_age':15000}))",dir],{cwd:repository,encoding:'utf8'});assert.equal(setup.status,0,setup.stderr);const query=JSON.parse(setup.stdout) as LocalQuery;
    const manifest=JSON.parse(await readFile(join(dir,'world',query.world_pack_sha256,'manifest.json'),'utf8')) as {database_sha256:string};const plan=await compileTutorialPlan(new LocalAssertionsClient({repository,database:join(dir,'agent.sqlite'),python}),query,manifest.database_sha256);
    let at=100,seq=0,issued=0,acted=false;const logs:Array<{kind:string;data:unknown}>=[],owner=new MemoryOwner(),emitter=new EventEmitter();
    const next=()=>{const s=sample();s.seq=++seq;s.memory_frame.seq=seq;s.memory_frame.frame_id=`frame-${seq}`;s.memory_frame.windows_clock_id=query.as_of_clock.clock_id;s.window.pid=query.session.pid;s.window.start_ticks=query.session.start_ticks;s.window.hwnd=query.session.hwnd;s.window.class=query.session.class;s.window.executable=query.session.executable;s.memory_frame.target={...query.session,windows_session_id:1};delete(s.memory_frame.target as unknown as {session_id?:number}).session_id;s.memory_frame.source_qpc_ms=s.capture.started_qpc_ms=900001+seq*100;s.capture.request_received_qpc_ms=s.memory_frame.request_received_qpc_ms=900000+seq*100;s.capture.arrived_qpc_ms=900002+seq*100;s.capture.finished_qpc_ms=900003+seq*100;s.local_clock.at_ms=900007+seq*100;s.input_state.sampled_qpc_ms=900006+seq*100;Object.assign(s.processing_timing,{request_ms:s.capture.request_received_qpc_ms,frame_arrived_ms:s.capture.arrived_qpc_ms,roi_started_ms:s.capture.arrived_qpc_ms,roi_finished_ms:s.capture.finished_qpc_ms,cv_started_ms:s.capture.finished_qpc_ms,cv_finished_ms:900005+seq*100,response_ms:s.local_clock.at_ms});if(!acted){s.cv.dialog_absence={status:'known',dialog_open:false,coverage_complete:true,calibration_sha256:absence,regions:[{id:'dialog_absence',matched:true,live_rect:{x:0,y:0,width:450,height:720}}]};s.memory_frame.rois.push({id:'dialog-absence-dialog_absence',x:0,y:0,width:450,height:720,sha256:absence,calibration_id:'reviewed-dialog-absence',calibration_sha256:absence});}at++;owner.receive(s,at,at);return{sample:s,started_at_ms:at,received_at_ms:at};};
    const sessionId='11111111-1111-4111-8111-111111111111';const r=(id:string,op:NativeReceipt['op']='execute'):NativeReceipt=>({...native(op),id,session_id:sessionId,status:op==='execute'?'completed':'ok',input:{status:'released',events_requested:op==='execute'?3:0,events_inserted:op==='execute'?3:0,released:true},timing:{clock:'windows_qpc',started_ms:900300,finished_ms:900360},...(op==='execute'?{input_timing:{clock:'windows_qpc' as const,first_send_started_ms:900320,first_send_finished_ms:900321,last_send_finished_ms:900360}}:{})});
    const client=Object.assign(emitter,{sample:async()=>next(),evidence:async()=>{const b=next(),e=fullEvidence(b.sample);e.ocr={status:'available',raw_text_retained:false,items:[{text:'吉安娜·普罗德摩尔',x:100,y:100,width:200,height:30},{text:'接受',x:100,y:600,width:60,height:30}]};return{...e,bracket:b};},validateBracket:owner.validateBracket.bind(owner),bindSource:async()=>{},sessionId,ready:{protocol:'wow-input',version:1,type:'ready',session_id:sessionId,executor_pid:1,watchdog_pid:2,window:{hwnd:query.session.hwnd,pid:99,client_width:1000,client_height:800,focused:true},capabilities:{timeline:true,keys:[],max_duration_ms:5000,heartbeat_lease_ms:1000},local_clock:{domain:'windows-qpc',at_ms:900000}},execute:async(_action:unknown,options?:{id?:string})=>{issued++;acted=true;at+=60;return r(options!.id!);},cancel:async()=>r('cancel','cancel'),releaseAll:async()=>r('release','release_all')}) as unknown as ResidentClient;
    const registry=new MemoryFrameRegistry(owner),collector=new ResidentTutorialCollector({client,registry,runId:'run',now:()=>at,calibrationSha256:cal,absenceCalibrationSha256:absence,append:async(kind,data)=>{logs.push({kind,data});},saveEvidence:async(e)=>({path:'/contract-fixture.png',sha256:e.artifact.sha256})});const first=await collector.collect();
    const profile=parseBodyProfile({protocol:'wow-body-profile',version:1,id:'contract',revision:1,character_id:null,layout_id:first.bracket.sample.memory_frame.layout_id,bindings_sha256:bodyBindingsSha256({bindings:{},abilities:{}}),source:{build:'12.1.0.69933',locale:'zh_CN',binding_artifact_sha256:null},mode_field:'player.mode',mouse_mode_field:'input.mouse_mode',bindings:{},abilities:{},capabilities:['screen_interact'],mouse_look_button:null,mouse_look_modes:[]});const trace=new TraceRecorder({traceId:'run',clock:()=>({domain:'coordinator-monotonic',id:'fixture',ms:at})});
    const result=await runTutorial({plan,profile,runId:'run',hand:client,mode:'live',finiteInputAuthorized:true,signal:new AbortController().signal,now:()=>at,currentSourceClock:()=>collector.sourceClock(),maximumLocalAge:15000,currentIdentity:()=>({task_id:plan.task.id,task_revision:1,run_epoch:1}),expectedWindow:first.observation.window!,collect:()=>collector.collect(),collectEffect:()=>collector.collectEffect(),memoryProofVerifier:registry.verify,bindSource:(b,i,c)=>collector.bindSource(b,i,c),saveObservations:false,windowsClockId:'fixture-qpc',trace,append:async(kind,data)=>{logs.push({kind,data});}});
    assert.equal(result.result.status,'completed',result.result.reason);assert.equal(issued,1);assert.equal(result.next_task_started,false);assert.equal(logs.filter(l=>l.kind==='layer_command_link').length,1);assert.ok(logs.some(l=>l.kind==='tutorial_plan_bound'));assert.equal(trace.records().filter(r=>r.kind==='mark'&&r.phase==='input_issued').length,1);assert.equal(trace.records().filter(r=>r.kind==='mark'&&r.phase==='effect_confirmed').length,1);
  }finally{await rm(dir,{recursive:true,force:true});}
});
test('cancel entry refuses foreign or reused coordinator before emitting a signal',async()=>{let main=repository;try{const m=/^gitdir:\s*(.+)\s*$/.exec(await readFile(join(repository,'.git'),'utf8'));if(m)main=resolve(repository,m[1]!,'../../..');}catch{}const dir=join(main,'out',`tutorial-cancel-fixture-${randomUUID()}`);await mkdir(join(main,'out'),{recursive:true});const entry=resolve(repository,'agent/src/tutorial/cli.ts');await writeFile(`${dir}.control.json`,JSON.stringify({protocol:'wow-tutorial-process-lease',version:1,directory:dir,pid:process.pid,start_ticks:'invalid-fixture',command_sha256:'a'.repeat(64),entry}));try{await assert.rejects(tutorialMain(['cancel','--run-dir',dir],repository),/pid_reused_or_foreign/);}finally{await rm(`${dir}.control.json`);}});
function blockedCold():RecoveryResult{return{protocol:'wow-session-recovery',version:1,run_id:'explicit-cold-contract-fixture',mode:'live',command:'recover',status:'blocked',reason:'occluded_after_one_focus_click',elapsed_ms:100,action_attempts:1,input_issued:1,input_count_scope:'known',effects_confirmed:0,release:'confirmed',goal_effect:'unverified',models:{visual:0,jev:0,brain:0},decision_owner:'code_state_machine_root_supervised',evidence_scope:'interactive_bridge',events:[],trace:[{kind:'mark',trace_id:'cold',action_id:'input-1',phase:'input_attempt',timing_kind:'measured',stamp:{domain:'coordinator-monotonic',id:'cold',ms:1},meta:{}},{kind:'mark',trace_id:'cold',action_id:'input-1',phase:'input_issued',timing_kind:'measured',stamp:{domain:'windows-qpc',id:'qpc',ms:10001},meta:{effect_confirmed:false}}],last_observation:null};}
test('cold recovery already issued one input then blocked retains terminal result and total count',()=>{const cold=parseColdRecovery(JSON.stringify(blockedCold()),1);assert.equal(cold.result!.status,'blocked');assert.equal(coldRecoveryAllowsTutorial(cold),false);const c=tutorialInputCounts(cold,[],[],null);assert.equal(c.cold.action_attempts,1);assert.equal(c.cold.input_issued,1);assert.equal(c.hot.input_issued,0);assert.equal(c.total.input_issued,1);assert.equal(c.total.input_count_scope,'known');});
test('spawned cold output parse/schema failure is an unknown lower bound; never known zero',()=>{for(const text of ['truncated',JSON.stringify({...blockedCold(),input_issued:'1'}),JSON.stringify({...blockedCold(),evidence_scope:'simulated_ports'})]){const cold=parseColdRecovery(text,null);assert.equal(cold.result,null);const c=tutorialInputCounts(cold,[],[],null);assert.equal(c.total.input_issued,0);assert.equal(c.total.input_count_scope,'lower_bound');assert.equal(c.cold.input_attempt_count_scope,'lower_bound');}const c=tutorialInputCounts({started:false,result:null,exit_code:null,reason:'not_launched',source:'not_started'},[],[],null);assert.equal(c.total.input_count_scope,'known');});
test('saved cold summary preserves issued lower bound when stdout is unavailable',()=>{const cold=parseColdRecovery(JSON.stringify({...blockedCold(),input_count_scope:'lower_bound'}),1,'saved_summary');assert.equal(cold.source,'saved_summary');const c=tutorialInputCounts(cold,[],[],null);assert.equal(c.total.input_issued,1);assert.equal(c.total.input_count_scope,'lower_bound');});
test('actual positive hot receipt survives a later task exception, duplicate wrappers do not double count',()=>{const t=new TraceRecorder({traceId:'hot',clock:()=>({domain:'coordinator-monotonic',id:'hot',ms:10})});t.mark('input_attempt','sent',{});const r={...native('execute'),id:'sent',status:'completed' as const,input:{status:'released' as const,events_requested:3,events_inserted:3,released:true}};const c=tutorialInputCounts(null,t.records(),[r,r],null);assert.equal(c.hot.input_issued,1);assert.equal(c.hot.input_count_scope,'known');assert.equal(c.total.input_issued,1);});
test('cold and hot counts stay separate and missing hot terminal receipt preserves uncertainty',()=>{const cold=parseColdRecovery(JSON.stringify(blockedCold()),1),t=new TraceRecorder({traceId:'hot',clock:()=>({domain:'coordinator-monotonic',id:'hot',ms:10})});t.mark('input_attempt','pending',{});let c=tutorialInputCounts(cold,t.records(),[],null);assert.equal(c.cold.input_issued,1);assert.equal(c.hot.input_issued,0);assert.equal(c.total.input_issued,1);assert.equal(c.total.input_count_scope,'lower_bound');const r={...native('execute'),id:'pending',status:'completed' as const,input:{status:'released' as const,events_requested:3,events_inserted:3,released:true}};c=tutorialInputCounts(cold,t.records(),[r],{real_inputs:1,input_count_scope:'known'});assert.equal(c.total.input_issued,2);assert.equal(c.total.input_count_scope,'known');});
