import test from 'node:test';import assert from 'node:assert/strict';import {deflateSync} from 'node:zlib';import {createHash} from 'node:crypto';
import {verifyProposalPixels,independentProposalAnchors,decodeEvidencePng} from '../src/ui-skills/proposal-verification.js';
import {memoryFixture} from './fixtures/resident-memory.js';import {DEMO_SCOPE} from '../src/ui-skills/demo.js';import type {UiFrame,UiProposal} from '../src/ui-skills/types.js';import type {ResidentEvidence} from '../src/resident/protocol.js';
function crc(b:Buffer){let v=0xffffffff;for(const c of b){v^=c;for(let i=0;i<8;i++)v=v&1?0xedb88320^(v>>>1):v>>>1;}return(v^0xffffffff)>>>0;}
function png(flat=false){const w=40,h=20,head=Buffer.alloc(13);head.writeUInt32BE(w);head.writeUInt32BE(h,4);head[8]=8;head[9]=2;const raw=Buffer.alloc((w*3+1)*h);for(let y=0;y<h;y++)for(let x=0;x<w;x++)for(let c=0;c<3;c++)raw[y*(w*3+1)+1+x*3+c]=flat?30:(x+y)%2?200:30;const chunk=(name:string,b:Buffer)=>{const key=Buffer.from(name),length=Buffer.alloc(4),sum=Buffer.alloc(4);length.writeUInt32BE(b.length);sum.writeUInt32BE(crc(Buffer.concat([key,b])));return Buffer.concat([length,key,b,sum]);};return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',head),chunk('IDAT',deflateSync(raw)),chunk('IEND',Buffer.alloc(0))]);}
function fixture(flat=false){const bytes=png(flat),sha=createHash('sha256').update(bytes).digest('hex'),f=memoryFixture(),m=f.sample.memory_frame;m.client_width=40;m.client_height=20;const {windows_session_id,...target}=m.target;
 const source={observation_id:f.collected.observation.id,frame_id:m.frame_id,seq:m.seq,width:40,height:20,layout_id:m.layout_id,target:{...target,session_id:windows_session_id},clock:{domain:'windows-qpc' as const,clock_id:m.windows_clock_id,ticks:m.source_qpc_ms,unit:'ms' as const},capture:{path:'/tmp/synthetic-original.png',sha256:sha},producer:'resident_wgc' as const};
 const frame:UiFrame={source,collected:f.collected,scope:DEMO_SCOPE,state:null,elements:[],hard_stop:null,native_evidence:{sample:f.sample,artifact:{source_frame_id:m.frame_id,source_qpc_ms:m.source_qpc_ms,sha256:sha,width:40,height:20},ocr:{status:'available',items:[{text:'重新连接',x:3,y:3,width:8,height:3},{text:'退出游戏',x:25,y:3,width:8,height:3}]}} as unknown as ResidentEvidence};
 const proposal:UiProposal={source_observation_id:source.observation_id,source_frame_id:source.frame_id,state_id:'reconnect',skill_id:'reconnect',hard_stop:null,element:{id:'reconnect',purpose:'reconnect',label:'重新连接',bbox:{x:0,y:0,width:.45,height:.5},button:'left',duration_ms:80},signature_bbox:{x:0,y:0,width:.45,height:.5},signature_anchors:[{id:'other-control',bbox:{x:.55,y:0,width:.45,height:.5},label:'退出游戏',origin:'other_control'}],expected_to_state:'char_select',confidence:.98,prompt_sha256:'a'.repeat(64),prompt_version:'v4',result_sha256:'b'.repeat(64),provider:'Seed'};
 return{bytes,frame,proposal};}
test('actual PNG pixels and independent same-frame OCR verify proposal; coordinates alone do not',()=>{const f=fixture();assert.equal(decodeEvidencePng(f.bytes).rgb.length,40*20*3);const result=verifyProposalPixels(f.proposal,f.frame,f.bytes);assert.equal(result.status,'passed');assert.equal('input_authority'in result?result.input_authority:undefined,false);
 const flat=fixture(true);assert.equal(verifyProposalPixels(flat.proposal,flat.frame,flat.bytes).status,'failed');});
test('proposal rejects edited bytes, stale native identity and OCR outside the model bbox',()=>{for(const mutate of [(f:ReturnType<typeof fixture>)=>{f.bytes=Buffer.from(f.bytes);f.bytes[45]=f.bytes[45]!^1;},(f:ReturnType<typeof fixture>)=>{f.frame.source.target.pid++;},(f:ReturnType<typeof fixture>)=>{(f.frame.native_evidence!.ocr!.items as any[])[0].x=25;},(f:ReturnType<typeof fixture>)=>{f.frame.native_evidence!.sample.memory_frame.source_qpc_ms++;}]){const f=fixture();mutate(f);assert.equal(verifyProposalPixels(f.proposal,f.frame,f.bytes).status,'failed');}});
test('missing model anchors can use another observed control only after its own pixel/OCR verification',()=>{const f=fixture(),anchors=independentProposalAnchors({id:'reconnect',rect:f.proposal.element.bbox},{anchors:[],controls:[{id:'logout',status:'known',label:'退出游戏',rect:{x:.55,y:0,width:.45,height:.5},confidence:.98}]});assert.equal(anchors[0]!.origin,'other_control');f.proposal.signature_anchors=anchors;assert.equal(verifyProposalPixels(f.proposal,f.frame,f.bytes).status,'passed');(f.frame.native_evidence!.ocr!.items as any[]).pop();assert.equal(verifyProposalPixels(f.proposal,f.frame,f.bytes).status,'failed');});
test('anchor overlap and unsupported PNG encoding are rejected',()=>{const f=fixture();f.proposal.signature_anchors![0]!.bbox=f.proposal.element.bbox;assert.equal(verifyProposalPixels(f.proposal,f.frame,f.bytes).status,'failed');assert.throws(()=>decodeEvidencePng(Buffer.from('not png')),/invalid/);});
function existingTemplate(f:ReturnType<typeof fixture>){
 const image=decodeEvidencePng(f.bytes),part=(bbox:UiProposal['signature_bbox'])=>{const x=Math.floor(bbox.x*image.width),y=Math.floor(bbox.y*image.height),w=Math.ceil((bbox.x+bbox.width)*image.width)-x,h=Math.ceil((bbox.y+bbox.height)*image.height)-y,rgb=Buffer.alloc(32*16*3);for(let row=0;row<16;row++)for(let col=0;col<32;col++)for(let c=0;c<3;c++)rgb[(row*32+col)*3+c]=image.rgb[((y+Math.min(h-1,Math.floor((row+.5)*h/16)))*image.width+x+Math.min(w-1,Math.floor((col+.5)*w/32)))*3+c]!;return{bbox,template_width:32,template_height:16,rgb_base64:rgb.toString('base64'),template_sha256:createHash('sha256').update(rgb).digest('hex'),source_capture_sha256:f.frame.source.capture!.sha256,max_mean_abs_error:8,max_fraction_above_24:.05};};
 return{skill_id:'prior-reconnect',state_id:f.proposal.state_id,scope:f.frame.scope,status:'candidate' as const,hard_stop:false,review:{status:'pending' as const,reviewer:'seed',reviewed_at:'2026-10-07T00:00:00Z',reason:'source'},revision:1,confirmed_count:0,failure_streak:0,last_failure:null,element:f.proposal.element,signature:{...part(f.proposal.element.bbox),sha256:'a'.repeat(64),source:f.frame.source,anchors:[part(f.proposal.signature_anchors![0]!.bbox)]},expected_effect:null};
}
test('OCR miss can use exact existing control glyph template plus independently recomputed state anchors',()=>{
 const f=fixture(),known=existingTemplate(f);f.frame.native_evidence!.ocr={status:'available',items:[]};
 const result=verifyProposalPixels(f.proposal,f.frame,f.bytes,[known]);assert.equal(result.status,'passed');assert.equal('verification_path'in result?result.verification_path:undefined,'pixels_only_existing_control_template');
 assert.equal('measurements'in result?(result.measurements.control as any).mean_abs_error:undefined,0);assert.equal(verifyProposalPixels(f.proposal,f.frame,f.bytes).status,'failed');
});
test('pixel-only fallback cannot use wrong labeled glyph, stale layout, missing context or changed template SHA',()=>{
 for(const change of [(s:ReturnType<typeof existingTemplate>)=>{s.element={...s.element,label:'删除角色'};},(s:ReturnType<typeof existingTemplate>)=>{s.signature.source={...s.signature.source,layout_id:'old'};},(s:ReturnType<typeof existingTemplate>)=>{s.signature.anchors=[];},(s:ReturnType<typeof existingTemplate>)=>{s.signature.template_sha256='f'.repeat(64);},(s:ReturnType<typeof existingTemplate>)=>{s.signature.rgb_base64=Buffer.alloc(32*16*3,100).toString('base64');s.signature.template_sha256=createHash('sha256').update(Buffer.alloc(32*16*3,100)).digest('hex');}]){const f=fixture(),known=existingTemplate(f);f.frame.native_evidence!.ocr={status:'available',items:[]};change(known);assert.equal(verifyProposalPixels(f.proposal,f.frame,f.bytes,[known]).status,'failed');}
});
