import test from 'node:test';
import assert from 'node:assert/strict';
import {UiSkillRuntime} from '../src/ui-skills/runtime.js';
import {DEMO_SCOPE,createUiDemo,runUiOfflineDemo,demoSkill} from '../src/ui-skills/demo.js';
import {routeUi,findUiPath} from '../src/ui-skills/router.js';
import type {UiProposal} from '../src/ui-skills/types.js';
import {uiCharacterConditions,assertNativeDispatchSkill} from '../src/ui-skills/resident-adapter.js';
import {memorySample} from './fixtures/resident-memory.js';
import {BodyRuntime,type BodyHand} from '../src/actions/runtime.js';
import type {NativeReady,NativeReceipt} from '../src/hand/protocol.js';
import {parseBodyProfile} from '../src/actions/profile.js';
import {bodyProfile,bodySample} from './fixtures/actions-body.js';
const controller=()=>new AbortController();
const runtime=(d:ReturnType<typeof createUiDemo>,extra={})=>new UiSkillRuntime({run_id:'ui-test',mode:'simulated',authorized:true,reviewed_candidate_trial_authorized:true,scope:DEMO_SCOPE,...extra},d.ports);
test('two-round recognized enter/menu/logout closes loop without real input or simulated live promotion',async()=>{const r=await runUiOfflineDemo(2);assert.equal(r.status,'completed');assert.equal(r.rounds_completed,2);assert.equal(r.simulated_actions,6);assert.equal(r.native_inputs,0);assert.equal(r.game_effect,'unverified');assert.ok(r.skills.every(s=>s.status==='candidate'&&s.confirmed_simulated_count===2&&!s.live_promotion_eligible));assert.ok(r.events.some(e=>e.kind==='ui_skill_macro'));});
test('reflex requires unique active two-confirmed native match; ambiguity and failure use Jev',async()=>{const d=createUiDemo({active:true}),f=await d.ports.collect('hot',controller().signal);assert.equal(routeUi(f,d.skills,0).owner,'reflex');assert.equal(routeUi(f,d.skills,1).owner,'jev');assert.equal(routeUi(f,[...d.skills,{...d.skills[0]!,skill_id:'other'}],0).owner,'jev');d.skills[0]!.status='candidate';assert.equal(routeUi(f,d.skills,0,true).owner,'jev');assert.equal(routeUi(f,d.skills,2).owner,'seed');});
test('unavailable unknown route persists review of full current image and issues no input',async()=>{const d=createUiDemo({unknown:true}),r=await runtime(d).step(controller().signal);assert.equal(r.reason,'ui_review_required');assert.equal(d.executions,0);assert.equal(d.reviews.length,1);assert.equal(d.reviews[0]!.input_allowed,false);assert.ok(d.reviews[0]!.frame.capture?.sha256);assert.equal(d.releases,1);});
test('credentials/2FA/terms/update hard stops dominate reflex and all model ports',async()=>{for(const hardStop of ['credentials','two_factor','terms','update'] as const){const d=createUiDemo({active:true,hardStop}),r=await runtime(d).step(controller().signal);assert.equal(r.status,'blocked');assert.equal(r.reason,`hard_stop:${hardStop}`);assert.equal(d.executions,0);assert.equal(d.reviews.length,0);assert.equal(d.releases,1);}});
test('postchecks at local 0.5/1/3/8 points cannot infer effect from completed input',async()=>{const d=createUiDemo({effectFails:true}),r=await runtime(d).step(controller().signal);assert.equal(r.reason,'ui_effect_timeout');assert.equal(r.effect_confirmed,false);assert.equal(r.game_effect,'unverified');assert.equal(d.attempts[0]!.effect.status,'unverified');assert.equal(d.ports.now(),8060);assert.equal(d.executions,1);});
test('effect timeout is unverified and preserves true failure history instead of fabricating failure',async()=>{const d=createUiDemo({active:true,effectFails:true}),runner=runtime(d);assert.equal((await runner.step(controller().signal)).owner,'reflex');assert.equal(d.skills[0]!.failure_streak,0);assert.equal((await runner.step(controller().signal)).owner,'reflex');assert.equal(d.skills[0]!.status,'active');assert.ok(d.attempts.every(a=>a.outcome_class==='timeout'&&a.effect.status==='unverified'));assert.equal(d.executions,2);});
test('late model choice, changed element signature, and source revoke prevent dispatch',async()=>{for(const fault of ['old_model','element_changed','source_revoked']){const d=createUiDemo(),runner=runtime(d);if(fault==='old_model')d.ports.chooseJev=async r=>({status:'selected',skill_id:r.candidates[0]!.skill_id,source_observation_id:'old',source_frame_id:r.source.frame_id});else if(fault==='element_changed'){const original=d.ports.collect;let reads=0;d.ports.collect=async(...args)=>{const f=await original(...args);if(++reads>=2)f.elements[0]!.signature_sha256='f'.repeat(64);return f;};}else d.ports.owns=()=>false;const r=await runner.step(controller().signal);assert.equal(r.status,'blocked',fault);assert.equal(d.executions,0,fault);}});
test('unknown Seed can propose new candidate but must install and match current native source',async()=>{const d=createUiDemo({unknown:true});d.ports.chooseSeed=async r=>({status:'proposed',proposal:{source_observation_id:r.source.observation_id,source_frame_id:r.source.frame_id,state_id:'character_select',skill_id:'new-enter',hard_stop:null,element:{...d.skills[0]!.element,id:'new-enter'},signature_bbox:d.skills[0]!.element.bbox,expected_to_state:'world',confidence:1,prompt_sha256:'a'.repeat(64),result_sha256:'b'.repeat(64),provider:'Seed'}});const result=await runtime(d).step(controller().signal);assert.equal(result.status,'blocked');assert.equal(result.reason,'ui_review_required');assert.equal(d.executions,0);assert.equal(d.skills.at(-1)!.status,'pending_review');});
test('bounded BFS ignores disallowed scopes and unknown transitions',()=>{const skills=[demoSkill('a','a','b'),demoSkill('b','b','c')];assert.deepEqual(findUiPath(skills,DEMO_SCOPE,'a','c',8,64,true)?.map(s=>s.skill_id),['a','b']);assert.equal(findUiPath(skills,DEMO_SCOPE,'a','c',1),null);skills[1]!.expected_effect=null;assert.equal(findUiPath(skills,DEMO_SCOPE,'a','c',8,64,true),null);assert.throws(()=>findUiPath(skills,DEMO_SCOPE,'a','c',Infinity),/budget/);});
test('cancel and unconfirmed release stop before any next action; rounds only 2 or 5',async()=>{const d=createUiDemo(),c=controller();c.abort();const r=await runtime(d).step(c.signal);assert.equal(r.status,'cancelled');assert.equal(d.executions,0);const broken=createUiDemo({unconfirmedRelease:true});assert.equal((await runtime(broken).step(controller().signal)).reason,'ui_release_unconfirmed');await assert.rejects(runtime(d).practice(3 as 2,'character_select','world',controller().signal),/rounds/);});
test('review resume rejects fabricated original-source binding',async()=>{const d=createUiDemo({unknown:true}),runner=runtime(d),first=await runner.step(controller().signal);const r=await runner.step(controller().signal,null,{request_id:first.review_request!.request_id,reviewed_source_observation_id:'fake',reviewed_source_frame_id:first.review_request!.frame.frame_id,reviewed_capture_sha256:'b'.repeat(64),skill_id:'enter_world'});assert.equal(r.reason,'ui_review_resume_not_original');assert.equal(d.executions,0);});
test('ESC skill matches state anchor and actual skill without inventing a UI button',async()=>{const d=createUiDemo({active:true}),f=await d.ports.collect('hot',controller().signal);const key={...d.skills[0]!,skill_id:'esc-menu',action:{kind:'key' as const,keys:['ESC'] as ['ESC'],duration_ms:50}};f.elements=[];f.state!.signature_sha256=key.signature.sha256;f.skill_matches=[{skill_id:key.skill_id,signature_sha256:key.signature.sha256,active_qualified:true,negative_validation_sha256:'e'.repeat(64)}];assert.equal(routeUi(f,[key],0).owner,'reflex');f.skill_matches=[];assert.equal(routeUi(f,[key],0).owner,'seed');f.skill_matches=[{skill_id:key.skill_id,signature_sha256:key.signature.sha256,active_qualified:true,negative_validation_sha256:'e'.repeat(64)}];f.state!.signature_sha256='f'.repeat(64);assert.equal(routeUi(f,[key],0).owner,'seed');});
test('key duration/allowlist bound and quest purpose cannot enter generic UI input',async()=>{for(const fault of ['duration','quest']){const d=createUiDemo({active:true});if(fault==='quest')d.skills[0]!.element.purpose='npc_interact';else d.skills[0]!.action={kind:'key',keys:['ESC'],duration_ms:151};const collect=d.ports.collect;d.ports.collect=async(...args)=>{const f=await collect(...args);if(fault==='duration'){f.state!.signature_sha256=d.skills[0]!.signature.sha256;f.skill_matches=[{skill_id:d.skills[0]!.skill_id,signature_sha256:d.skills[0]!.signature.sha256}];}return f;};const result=await runtime(d).step(controller().signal);assert.equal(result.status,'blocked');assert.equal(d.executions,0);assert.equal(result.reason,fault==='duration'?'ui_key_or_wait_not_finite':'ui_gameplay_requires_layered_tutorial');}});
test('ENTER state action and wait remain bound to a native skill match',async()=>{const d=createUiDemo({active:true}),f=await d.ports.collect('hot',controller().signal);f.elements=[];const skill={...d.skills[0]!,action:{kind:'key' as const,keys:['ENTER'] as ['ENTER'],duration_ms:75}};f.state!.signature_sha256=skill.signature.sha256;f.skill_matches=[{skill_id:skill.skill_id,signature_sha256:skill.signature.sha256,active_qualified:true,negative_validation_sha256:'e'.repeat(64)}];assert.equal(routeUi(f,[skill],0).owner,'reflex');const wait={...skill,action:{kind:'wait' as const,duration_ms:500}};assert.equal(routeUi(f,[wait],0).owner,'reflex');});
test('loading uses finite configured late checks with real sample clocks and rejects >30 seconds',async()=>{const d=createUiDemo({effectFails:true}),runner=runtime(d,{effect_check_ms:[500,1000,3000,8000,15000,25000]});const r=await runner.step(controller().signal);assert.equal(r.reason,'ui_effect_timeout');const points=d.events.filter(e=>e.kind==='ui_effect_check').map(e=>e.data as {offset_ms:number;scheduled_coordinator_ms:number;requested_coordinator_ms:number;received_coordinator_ms:number;after_source:{clock:{ticks:number}}});assert.deepEqual(points.map(p=>p.offset_ms),[500,1000,3000,8000,15000,25000]);assert.ok(points.every(p=>p.requested_coordinator_ms>=p.scheduled_coordinator_ms&&p.received_coordinator_ms>=p.requested_coordinator_ms&&p.after_source.clock.ticks===p.received_coordinator_ms));assert.equal(d.executions,1);assert.throws(()=>runtime(createUiDemo(),{effect_check_ms:[30001]}),/check_budget/);});
test('enter-world Body dispatch rechecks the approved character after routing, preserving normal keys',async()=>{
  for(const changed of [false,true,'missing'] as const){
    const d=createUiDemo(),frame=await d.ports.collect('hot',controller().signal);const routing=bodySample('routing',100,'live');
    routing.observation.fields['ui.selected_character']={status:'known',value:{name:'小呵',class:'warrior',faction:'alliance'},source:'cv',captured_at_ms:100,source_observation_id:'routing'};frame.collected=routing;
    const conditions=uiCharacterConditions({...d.skills[0]!,state_id:'char_select',expected_effect:{state_id:'in_world',signature_sha256:null}},frame);assert.equal(conditions.length,1);
    let sends=0,seq=0;const ready:NativeReady={protocol:'wow-input',version:1,type:'ready',session_id:'fixture-hand',executor_pid:1,watchdog_pid:2,window:{hwnd:'0xabc',pid:99,client_width:1000,client_height:800,focused:true},capabilities:{keys:['ENTER'],max_duration_ms:5000,heartbeat_lease_ms:1000,timeline:true},local_clock:{domain:'windows-qpc',at_ms:9999999}};
    const receipt=(id:string,op:NativeReceipt['op']='execute'):NativeReceipt=>({protocol:'wow-input',version:1,type:'receipt',session_id:ready.session_id,id,op,status:op==='execute'?'completed':'ok',input:{status:'released',events_requested:op==='execute'?2:0,events_inserted:op==='execute'?2:0,released:true},effect:{status:'unknown'},timing:{clock:'windows_qpc',started_ms:9000000,finished_ms:9000001},local_clock:{domain:'windows-qpc',at_ms:9999999}});
    const hand:BodyHand={ready,sessionId:ready.session_id,execute:async(_a,o)=>{sends++;return receipt(o?.id??'fixture-id');},cancel:async()=>receipt('cancel','cancel'),releaseAll:async()=>receipt('release','release_all')};
    const profile=bodyProfile();const body=new BodyRuntime({profile:parseBodyProfile({...profile,capabilities:[...profile.capabilities,'ui_key']}),runId:'run',hand,now:()=>100,currentIdentity:()=>({task_id:'ui-practice',task_revision:1,run_epoch:0}),expectedWindow:routing.observation.window!,collect:async()=>{
      const sample=bodySample(`dispatch-${++seq}`,100,'live');sample.observation.fields['ui.state']={status:'known',value:{id:'char_select',confidence:1,signature_sha256:'c'.repeat(64),hard_stop:null},source:'cv',captured_at_ms:100,source_observation_id:sample.observation.id};
      if(changed!=='missing')sample.observation.fields['ui.selected_character']={status:'known',value:{name:changed?'其他角色':'小呵',class:'warrior',faction:'alliance'},source:'cv',captured_at_ms:100,source_observation_id:sample.observation.id};return sample;
    }});
    const result=await body.execute({kind:'ui_key',key:'ENTER',state_id:'char_select',duration_ms:50},{command_id:'enter-1',task_id:'ui-practice',task_revision:1,run_epoch:0,mode:'live',conditions,signal:controller().signal});
    assert.equal(sends,changed?0:1,`${String(changed)} ${result.reason}`);assert.equal(result.status,changed?'blocked':'completed',result.reason??'');
  }
});
test('selected Native key signature remains required while unrelated scene matches may change',()=>{
 const s=memorySample('chosen-key',1),expected={skill_id:'esc',signature_id:'sig-esc',state_id:'tutorial_attack_training',knowledge_sha256:'e'.repeat(64)};
 const selected={...expected,status:'candidate' as const,hard_stop:false,roi_sha256:'f'.repeat(64)};
 s.ui_skills={status:'known',state_id:expected.state_id,confidence:.6,matches:[selected],knowledge_sha256:'e'.repeat(64),hard_stop:false,started_qpc_ms:s.memory_frame.source_qpc_ms,finished_qpc_ms:s.local_clock.at_ms};
 assert.doesNotThrow(()=>assertNativeDispatchSkill(s,expected));s.ui_skills.matches.unshift({...selected,skill_id:'ground',signature_id:'sig-ground'});assert.doesNotThrow(()=>assertNativeDispatchSkill(s,expected));
 s.ui_skills.matches=s.ui_skills.matches.filter(m=>m.skill_id!=='ground');assert.doesNotThrow(()=>assertNativeDispatchSkill(s,expected));
 for(const fault of ['missing','signature','state','hard_stop','knowledge']){const x=structuredClone(s);if(fault==='missing')x.ui_skills!.matches=[];if(fault==='signature')x.ui_skills!.matches[0]!.signature_id='changed';if(fault==='state')x.ui_skills!.state_id='other';if(fault==='hard_stop')x.ui_skills!.hard_stop=true;if(fault==='knowledge')x.ui_skills!.knowledge_sha256='a'.repeat(64);assert.throws(()=>assertNativeDispatchSkill(x,expected),/selected_native_skill_changed/);}
});
test('pre-dispatch Body refusal keeps its reason without inventing run provenance or input',async()=>{
 const d=createUiDemo();d.skills[0]!.element.purpose='fixture_control';d.skills[0]!.element.id='fixture_button';d.skills[0]!.expected_effect={state_id:'game_menu',signature_sha256:'c'.repeat(64)};const collect=d.ports.collect;d.ports.collect=async(...args)=>{const f=await collect(...args);f.source.producer='resident_wgc';f.source.clock={domain:'windows-qpc',clock_id:'fault-fixture',ticks:100,unit:'ms'};f.source.target.session_id=1;return f;};
 d.ports.provenance=async skill=>({run_id:'ui-test',code_sha256:'a'.repeat(64),prompt_sha256:'b'.repeat(64),prompt_version:'fixture',knowledge_sha256:'c'.repeat(64),skill_revision:skill.revision});
 d.ports.execute=async()=>({status:'blocked',reason:'condition_failed:ui.skill_matches',started_at_ms:0,finished_at_ms:1,before_observation_id:null,after_observation_id:null,receipt:null,release:'confirmed',game_effect:'unverified',evidence_observation_ids:[],real_inputs:0,dispatch_frame:null});
 const r=await runtime(d,{mode:'live'}).step(controller().signal);assert.equal(r.reason,'condition_failed:ui.skill_matches');assert.equal(r.input_issued,false);assert.equal(r.release,'confirmed');
});
