import test from 'node:test';import assert from 'node:assert/strict';
import {unverifiedLayerAttempt} from '../src/ui-skills/layer-attempt.js';import {TimelineBuilder} from '../src/actions/timeline.js';import {demoSkill,DEMO_SCOPE} from '../src/ui-skills/demo.js';import {memoryFixture} from './fixtures/resident-memory.js';import type {UiFrame} from '../src/ui-skills/types.js';import type {ResidentReceipt} from '../src/resident/protocol.js';import type {NativeTimeline} from '../src/hand/protocol.js';
function fixture(action:NativeTimeline){const f=memoryFixture(),m=f.sample.memory_frame,{windows_session_id,...target}=m.target;const before:UiFrame={collected:f.collected,scope:DEMO_SCOPE,state:null,elements:[],hard_stop:null,source:{observation_id:f.collected.observation.id,frame_id:m.frame_id,seq:m.seq,width:m.client_width,height:m.client_height,layout_id:m.layout_id,target:{...target,session_id:windows_session_id},clock:{domain:'windows-qpc',clock_id:m.windows_clock_id,ticks:m.source_qpc_ms,unit:'ms'},capture:null,producer:'resident_wgc'}};
 const receipt={id:'actual-input',source:m,intent:{observation_id:before.source.observation_id},native:{id:'actual-input',op:'execute',status:'completed',input:{events_inserted:action.events.length,events_requested:action.events.length,released:true},input_timing:{clock:'windows_qpc',first_send_finished_ms:m.source_qpc_ms+10}}} as ResidentReceipt;
 return{skill:demoSkill('actual-skill','look','world'),before,after:null,receipt,receipt_artifact:{path:'/tmp/original-receipt',sha256:'a'.repeat(64)},compiled_action:action,provenance:{run_id:'registered',code_sha256:'b'.repeat(64),knowledge_sha256:'c'.repeat(64),prompt_sha256:'d'.repeat(64),prompt_version:'no_prompt-v1',skill_revision:1}};}
test('layer motion preserves actual W150 and 950ms drag, original sample and issued-only latency',()=>{
 const move=new TimelineBuilder(150).press(['W'],0,150).build(),camera=new TimelineBuilder(950).absoluteMouseMove(700,620,0).down({button:'right'},150,800);for(let i=0;i<8;i++)camera.relativeMouseMove(i<4?30:-30,0,250+i*100);camera.up({button:'right'},950);
 for(const [kind,compiled] of [['move',move],['drag',camera.build()]] as const){const r=unverifiedLayerAttempt({...fixture(compiled),kind});assert.equal(r.actual_action!.kind,kind);assert.deepEqual(r.actual_action!.compiled_action,compiled);assert.equal(r.effect.status,'unverified');assert.equal(r.latency.observe_to_input_ms,10);assert.equal(r.latency.observe_to_effect_ms,null);assert.equal(r.before_native_sample!.memory_frame.frame_id,r.before.frame_id);}
});
test('layer recorder rejects changed source and cannot relabel a wait or arbitrary key as movement',()=>{
 const f=fixture(new TimelineBuilder(150).press(['W'],0,150).build());f.receipt.source=structuredClone(f.receipt.source!);f.receipt.source.source_qpc_ms--;assert.throws(()=>unverifiedLayerAttempt({...f,kind:'move'}),/binding/);
 const bad=fixture(new TimelineBuilder(150).press(['ENTER'],0,150).build());assert.throws(()=>unverifiedLayerAttempt({...bad,kind:'move'}),/move_primitive/);assert.throws(()=>unverifiedLayerAttempt({...bad,kind:'drag'}),/drag_primitive/);
});
