PRAGMA foreign_keys=ON;
CREATE TABLE metadata(key TEXT PRIMARY KEY, value TEXT NOT NULL) STRICT;
CREATE TABLE source_revision(sha256 TEXT PRIMARY KEY, payload TEXT NOT NULL CHECK(json_valid(payload))) STRICT;
CREATE TABLE source_artifact(sha256 TEXT PRIMARY KEY, media_type TEXT NOT NULL, byte_count INTEGER NOT NULL CHECK(byte_count>=0)) STRICT;
CREATE TABLE entity(namespace TEXT NOT NULL, kind TEXT NOT NULL, native_id INTEGER NOT NULL CHECK(native_id>0), content_expansion TEXT, PRIMARY KEY(namespace,kind,native_id)) STRICT;
CREATE TABLE assertion(sha256 TEXT PRIMARY KEY, namespace TEXT NOT NULL, kind TEXT NOT NULL, native_id INTEGER NOT NULL, predicate TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('known','unknown','unsupported','not_present')), value_json TEXT NOT NULL CHECK(json_valid(value_json)), source_sha256 TEXT NOT NULL REFERENCES source_revision(sha256), artifact_sha256 TEXT REFERENCES source_artifact(sha256), locator TEXT NOT NULL, observed_at TEXT NOT NULL, condition_json TEXT NOT NULL CHECK(json_valid(condition_json)), verification TEXT NOT NULL CHECK(verification IN ('reference_only','source_verified','locally_verified')), payload TEXT NOT NULL CHECK(json_valid(payload)), FOREIGN KEY(namespace,kind,native_id) REFERENCES entity(namespace,kind,native_id)) STRICT;
CREATE INDEX assertion_entity ON assertion(namespace,kind,native_id,predicate,sha256);
CREATE TABLE applicability(assertion_sha256 TEXT NOT NULL REFERENCES assertion(sha256), version_key TEXT NOT NULL CHECK(json_valid(version_key)), proof_json TEXT NOT NULL CHECK(json_valid(proof_json)), PRIMARY KEY(assertion_sha256,version_key)) STRICT;
CREATE INDEX applicability_version ON applicability(version_key);
CREATE TABLE localized_text(assertion_sha256 TEXT PRIMARY KEY REFERENCES assertion(sha256), namespace TEXT NOT NULL, kind TEXT NOT NULL, native_id INTEGER NOT NULL, locale TEXT NOT NULL, role TEXT NOT NULL, text TEXT NOT NULL, normalized_text TEXT NOT NULL) STRICT;
CREATE INDEX text_lookup ON localized_text(namespace,kind,locale,normalized_text);
CREATE TABLE text_token(token TEXT NOT NULL, assertion_sha256 TEXT NOT NULL REFERENCES localized_text(assertion_sha256), PRIMARY KEY(token,assertion_sha256)) STRICT;
CREATE TABLE condition_expr(sha256 TEXT PRIMARY KEY, payload TEXT NOT NULL CHECK(json_valid(payload))) STRICT;
CREATE TABLE quest_relation(assertion_sha256 TEXT NOT NULL REFERENCES assertion(sha256), ordinal INTEGER NOT NULL, namespace TEXT NOT NULL, quest_id INTEGER NOT NULL, relation TEXT NOT NULL, condition_sha256 TEXT NOT NULL REFERENCES condition_expr(sha256), PRIMARY KEY(assertion_sha256,ordinal)) STRICT;
CREATE TABLE quest_objective(assertion_sha256 TEXT NOT NULL REFERENCES assertion(sha256), ordinal INTEGER NOT NULL, namespace TEXT NOT NULL, quest_id INTEGER NOT NULL, objective_type TEXT NOT NULL, target_namespace TEXT, target_kind TEXT, target_id INTEGER, required_count INTEGER CHECK(required_count>0), PRIMARY KEY(assertion_sha256,ordinal), FOREIGN KEY(target_namespace,target_kind,target_id) REFERENCES entity(namespace,kind,native_id)) STRICT;
CREATE TABLE quest_giver(assertion_sha256 TEXT NOT NULL REFERENCES assertion(sha256), ordinal INTEGER NOT NULL, namespace TEXT NOT NULL, quest_id INTEGER NOT NULL, role TEXT NOT NULL CHECK(role IN ('starter','finisher')), giver_namespace TEXT NOT NULL, giver_kind TEXT NOT NULL, giver_id INTEGER NOT NULL, PRIMARY KEY(assertion_sha256,ordinal), FOREIGN KEY(giver_namespace,giver_kind,giver_id) REFERENCES entity(namespace,kind,native_id)) STRICT;
CREATE TABLE location(assertion_sha256 TEXT NOT NULL REFERENCES assertion(sha256), ordinal INTEGER NOT NULL, coordinate_space TEXT NOT NULL, map_namespace TEXT NOT NULL, map_kind TEXT NOT NULL, map_id INTEGER NOT NULL, floor INTEGER, x REAL NOT NULL, y REAL NOT NULL, z REAL, accuracy REAL CHECK(accuracy>=0), transform_revision TEXT, phase_json TEXT NOT NULL CHECK(json_valid(phase_json)), PRIMARY KEY(assertion_sha256,ordinal), FOREIGN KEY(map_namespace,map_kind,map_id) REFERENCES entity(namespace,kind,native_id)) STRICT;
CREATE INDEX location_map ON location(map_namespace,map_kind,map_id,floor);
CREATE VIRTUAL TABLE location_rtree USING rtree(row_id,min_x,max_x,min_y,max_y);
CREATE TABLE spatial_index(row_id INTEGER PRIMARY KEY, assertion_sha256 TEXT NOT NULL, ordinal INTEGER NOT NULL, FOREIGN KEY(assertion_sha256,ordinal) REFERENCES location(assertion_sha256,ordinal)) STRICT;
CREATE TABLE guide_step(assertion_sha256 TEXT PRIMARY KEY REFERENCES assertion(sha256), payload TEXT NOT NULL CHECK(json_valid(payload))) STRICT;
CREATE TABLE route_edge(assertion_sha256 TEXT PRIMARY KEY REFERENCES assertion(sha256), payload TEXT NOT NULL CHECK(json_valid(payload))) STRICT;
CREATE TABLE achievement_criteria(assertion_sha256 TEXT PRIMARY KEY REFERENCES assertion(sha256), condition_sha256 TEXT NOT NULL REFERENCES condition_expr(sha256)) STRICT;
CREATE TABLE encounter_mechanic(assertion_sha256 TEXT PRIMARY KEY REFERENCES assertion(sha256), payload TEXT NOT NULL CHECK(json_valid(payload))) STRICT;
CREATE TABLE migration_v1(assertion_sha256 TEXT PRIMARY KEY, payload TEXT NOT NULL CHECK(json_valid(payload))) STRICT;
CREATE TABLE migration_mapping(v1_sha256 TEXT NOT NULL REFERENCES migration_v1(assertion_sha256), v2_sha256 TEXT NOT NULL REFERENCES assertion(sha256), converter_version TEXT NOT NULL, PRIMARY KEY(v1_sha256,v2_sha256)) STRICT;
CREATE TABLE import_batch(sha256 TEXT PRIMARY KEY, record_count INTEGER NOT NULL) STRICT;
PRAGMA user_version=2;
