-- 由 tools/gen_schema_lua.py 从 protocol/schema_v1.json 生成，不要手改。
JevBridge = JevBridge or {}
JevBridge.SchemaV1 = {
  version = 1,
  fields = {
    { name = "t_ms", type = "u32" },
    { name = "caps", type = "bits16", bits = { "facing", "speed", "map_area", "map_pos", "aura_spell_id" } },
    { name = "p_flags", type = "bits16", bits = { "in_combat", "dead", "ghost", "casting", "channeling", "mounted", "resting", "moving", "swimming", "flying", "indoors", "stealthed", "has_target" } },
    { name = "p_hp", type = "u32" },
    { name = "p_hp_max", type = "u32" },
    { name = "p_power", type = "u32" },
    { name = "p_power_max", type = "u32" },
    { name = "p_power_type", type = "u8" },
    { name = "p_level", type = "u8" },
    { name = "p_cast_hash", type = "u24" },
    { name = "p_cast_rem_ms", type = "u16" },
    { name = "p_map_id", type = "u16" },
    { name = "p_map_x", type = "u16" },
    { name = "p_map_y", type = "u16" },
    { name = "p_facing", type = "u16" },
    { name = "p_speed", type = "u16" },
    { name = "t_flags", type = "bits16", bits = { "exists", "hostile", "dead", "casting", "channeling", "interruptible", "is_player", "tapped_by_other", "targeting_me" } },
    { name = "t_hp_pct", type = "u16" },
    { name = "t_level", type = "u8" },
    { name = "t_class", type = "u8" },
    { name = "t_guid", type = "u32" },
    { name = "t_cast_hash", type = "u24" },
    { name = "t_cast_rem_ms", type = "u16" },
    { name = "t_range", type = "u8" },
    { name = "gcd_rem_ms", type = "u16" },
    {
      name = "actions",
      type = "array",
      count = 12,
      fields = {
        { name = "cd_ms", type = "u16" },
        { name = "flags", type = "bits8", bits = { "has", "usable", "no_mana", "in_range", "out_of_range", "current", "auto_repeat" } },
      },
    },
    {
      name = "p_buffs",
      type = "array",
      count = 8,
      fields = {
        { name = "id", type = "u24" },
        { name = "rem_ds", type = "u16" },
        { name = "stacks", type = "u8" },
        { name = "flags", type = "bits8", bits = { "mine" } },
      },
    },
    {
      name = "p_debuffs",
      type = "array",
      count = 4,
      fields = {
        { name = "id", type = "u24" },
        { name = "rem_ds", type = "u16" },
        { name = "stacks", type = "u8" },
        { name = "flags", type = "bits8", bits = { "mine" } },
      },
    },
    {
      name = "t_debuffs",
      type = "array",
      count = 8,
      fields = {
        { name = "id", type = "u24" },
        { name = "rem_ds", type = "u16" },
        { name = "stacks", type = "u8" },
        { name = "flags", type = "bits8", bits = { "mine" } },
      },
    },
    {
      name = "t_buffs",
      type = "array",
      count = 4,
      fields = {
        { name = "id", type = "u24" },
        { name = "rem_ds", type = "u16" },
        { name = "stacks", type = "u8" },
        { name = "flags", type = "bits8", bits = { "mine" } },
      },
    },
  },
}
