// Fault-injection fixture for production perception/eligibility math. No
// desktop, capture, process launch, database, network or input operation.
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;

static class UiSkillGovernanceFixture
{
    static readonly List<object> Results=new List<object>();
    static readonly Dictionary<string,object> Scope=ResidentWire.Obj("target_scope","retail_wow","build","offline-fixture","locale","zhCN","size_bucket","384x240","ui_scale",1);
    const int Width=384,Height=240;
    static string Sha(string text){return ResidentWire.Hash(Encoding.UTF8.GetBytes(text));}
    static Dictionary<string,object> Box(int x,int y,int w,int h){return ResidentWire.Obj("x",(double)x/Width,"y",(double)y/Height,"width",(double)w/Width,"height",(double)h/Height);}
    static byte[] Scene(){var p=new byte[Width*Height*4];Paint(p,new Rectangle(0,0,Width,Height),20,30,130);Paint(p,new Rectangle(16,16,64,32),210,25,20);Paint(p,new Rectangle(288,16,64,32),20,210,25);return p;}
    static void Paint(byte[] pixels,Rectangle rect,int r,int g,int b){for(int y=rect.Top;y<rect.Bottom;y++)for(int x=rect.Left;x<rect.Right;x++){int p=(y*Width+x)*4;pixels[p]=(byte)b;pixels[p+1]=(byte)g;pixels[p+2]=(byte)r;pixels[p+3]=255;}}
    static byte[] Crop(byte[] pixels,Rectangle rect){var outPixels=new byte[rect.Width*rect.Height*4];for(int y=0;y<rect.Height;y++)Buffer.BlockCopy(pixels,((y+rect.Y)*Width+rect.X)*4,outPixels,y*rect.Width*4,rect.Width*4);return outPixels;}
    static Dictionary<string,object> Template(int x,int y,int r,int g,int b){var rgb=new byte[32*16*3];for(int i=0;i<rgb.Length;i+=3){rgb[i]=(byte)r;rgb[i+1]=(byte)g;rgb[i+2]=(byte)b;}
        return ResidentWire.Obj("bbox",Box(x,y,64,32),"template_width",32,"template_height",16,"rgb_base64",Convert.ToBase64String(rgb),"template_sha256",ResidentWire.Hash(rgb),"max_mean_abs_error",8,"max_fraction_above_24",.05,"source_capture_sha256",Sha("source-a"));
    }
    static Dictionary<string,object> Guard(){return ResidentWire.Obj("method","neutral_panel_components_v1","algorithm_sha256",UiSkillVision.ModalAlgorithmSha(),"source_capture_sha256",Sha("source-a"),"expected_panels",new object[0],"negative_artifacts",new object[]{ResidentWire.Obj("path","offline-unknown-modal.png","sha256",Sha("unknown-modal"))},"review",ResidentWire.Obj("status","approved","reviewer","claude","report_sha256",Sha("approved-fixture-audit")));}
    static Dictionary<string,object> Skill(string id,string state,int r,int g,int b,string status){var sig=Template(16,16,r,g,b);sig["signature_id"]="signature-"+id;sig["sha256"]=Sha("immutable-signature-"+id);sig["source_capture_sha256"]=Sha("source-"+id);sig["review"]=ResidentWire.Obj("status","approved","reviewer","claude");sig["anchors"]=new object[]{Template(288,16,20,210,25)};
        var original=Clone(sig);original.Remove("review");original.Remove("sha256");original.Remove("signature_id");sig["sha256"]=Sha(ResidentWire.Encode(original));sig["signature_id"]="ui-signature-"+((string)sig["sha256"]).Substring(0,24);
        if(id=="a")sig["modal_guard"]=Guard();return ResidentWire.Obj("skill_id",id,"state_id",state,"status",status,"hard_stop",false,"scope",Scope,"review",ResidentWire.Obj("status","approved","reviewer","claude"),"element",ResidentWire.Obj("id","button-"+id,"purpose","fixture_control","bbox",Box(16,16,64,32),"button","left","duration_ms",80),"signature",sig,"modal_guard",id=="a"?Guard():null,"governance",ResidentWire.Obj("activation_frozen",false,"review_eligible",true,"objective_eligible",true,"user_revoked",false,"metrics",ResidentWire.Obj("ready",true,"qualified_count",2,"distinct_runs",2,"recent_count",2,"recent_success_rate",1)));
    }
    static Dictionary<string,object> Snapshot(){return ResidentWire.Obj("protocol","wow-ui-skill-snapshot","version",1,"skills",new object[]{Skill("a","state-a",210,25,20,"active"),Skill("b","state-b",20,25,210,"candidate")});}
    static Dictionary<string,object> Frame(string source){return ResidentWire.Obj("observation_id","offline-"+source,"frame_id","frame-1","seq",1,"width",Width,"height",Height,"layout_id",Sha("fixture-layout"),"clock",ResidentWire.Obj("domain","coordinator-monotonic","clock_id","offline","ticks",1,"unit","ms"),"target",ResidentWire.Obj("pid",1,"start_ticks","1","hwnd","0x1","class","offline","executable","offline","session_id",1),"capture",ResidentWire.Obj("path","offline-"+source+".png","sha256",Sha("source-"+source)),"producer","simulation");}
    static Dictionary<string,object> Negative(Dictionary<string,object> snapshot){var corpus=new object[]{ResidentWire.Obj("state_id","state-a","scope",Scope,"frame",Frame("a")),ResidentWire.Obj("state_id","state-b","scope",Scope,"frame",Frame("b"))};
        var algorithm=ResidentWire.Obj("id","ui-cell-center-rgb-32x16-v1","grid_width",32,"grid_height",16,"channel_order","RGB","bbox_rounding","floor-left-top-ceil-right-bottom","sampling","floor-cell-center","fraction_error_threshold",24);
        var skill=ResidentWire.Map(((object[])snapshot["skills"])[0]);var signature=ResidentWire.Map(skill["signature"]);var original=Clone(signature);original.Remove("sha256");original.Remove("signature_id");original.Remove("review");original.Remove("modal_guard");string originalText=ResidentWire.Encode(original),skillText=ResidentWire.Encode(skill);
        var row=ResidentWire.Obj("skill_id","a","state_id","state-a","scope",Scope,"signature_sha256",signature["sha256"],"source_skill_canonical",skillText,"source_skill_sha256",Sha(skillText),"signature_original_canonical",originalText,"own_positive",true,"negatives",new object[]{ResidentWire.Obj("state_id","state-b","capture_sha256",Sha("source-b"),"capture_path","offline-b.png","matched",false,"pass",true)},"complete",true,"pass",true,"review_eligible",true,"objective_eligible",true,"user_revoked",false,"metrics",ResidentWire.Map(skill["governance"])["metrics"],"approved_audit_sha256",Sha("approved-fixture-audit"),"audit_reviewer","claude","activation_frozen",false);
        return ResidentWire.Obj("protocol","wow-ui-negative-validation","version",1,"snapshot_sha256",Sha(ResidentWire.Encode(snapshot)),"algorithm",algorithm,"corpus_sha256",Sha(ResidentWire.Encode(corpus)),"corpus",corpus,"skills",new object[]{row},"quarantine",new object[0]);
    }
    static Dictionary<string,object> Clone(Dictionary<string,object> map){return ResidentWire.Map(ResidentWire.Decode(ResidentWire.Encode(map)));}
    static Dictionary<string,object> Memory(){return ResidentWire.Obj("client_width",Width,"client_height",Height,"frame_id","offline-frame-1","source_qpc_ms",100,"layout_id",Sha("fixture-layout"));}
    static UiSkillVision Load(Dictionary<string,object> snapshot,Dictionary<string,object> negatives){string s=ResidentWire.Encode(snapshot);var vision=new UiSkillVision();if(negatives==null)vision.Load(s,Sha(s));else{string n=ResidentWire.Encode(negatives);vision.LoadVerified(s,Sha(s),n,Sha(n));}return vision;}
    static Dictionary<string,object> Match(UiSkillVision vision,byte[] pixels){var regions=vision.Regions(Width,Height,Scope);var rois=new List<WgcCapture.Roi>();foreach(var region in regions){var p=Crop(pixels,region.Rectangle);rois.Add(new WgcCapture.Roi{Pixels=p,Rectangle=region.Rectangle,Hash=ResidentWire.Hash(p)});}return vision.Match(rois,regions,Scope,Memory());}
    static bool Qualified(Dictionary<string,object> match){return ((IList<object>)match["matches"]).Any(row=>ResidentWire.Bool(ResidentWire.Map(row),"active_qualified"));}
    static void Check(string name,Func<bool> test){ResidentWire.Need(test(),"governance_case_failed:"+name);Results.Add(ResidentWire.Obj("case",name,"pass",true));}
    static bool Throws(Action action){try{action();return false;}catch(InvalidOperationException){return true;}}
    static Dictionary<string,object> Mouse(){return ResidentWire.Obj("kind","timeline","duration_ms",230,"events",new object[]{ResidentWire.Obj("kind","absolute_mouse_move","at_ms",0,"x",48,"y",32),ResidentWire.Obj("kind","button_down","at_ms",150,"button","left"),ResidentWire.Obj("kind","button_up","at_ms",230,"button","left")});}
    static int Main(){try{Console.OutputEncoding=new UTF8Encoding(false);var snapshot=Snapshot();var negative=Negative(snapshot);var scene=Scene();var vision=Load(snapshot,negative);var actual=Match(vision,scene);
        Check("complete_objective_sidecar_can_qualify_fixture_logic",()=>Qualified(actual)&&ResidentWire.Text(ResidentWire.Map(actual["modal"]),"status")=="clear");
        Check("plain_load_never_qualifies_active",()=>!Qualified(Match(Load(snapshot,null),scene)));
        var binding=ResidentWire.Obj("skill_id","a","route","reflex","knowledge_sha256",vision.KnowledgeSha);
        Check("reviewed_mouse_primitive_bound",()=>{vision.VerifyReflex(binding,actual,Mouse(),Memory());return true;});var wrongMouse=Mouse();ResidentWire.Map(((object[])wrongMouse["events"])[0])["x"]=49;
        Check("changed_mouse_point_rejected",()=>Throws(()=>vision.VerifyReflex(binding,actual,wrongMouse,Memory())));
        var changedKnowledge=Clone(binding);changedKnowledge["knowledge_sha256"]=Sha("other");Check("changed_knowledge_rejected",()=>Throws(()=>vision.VerifyReflex(changedKnowledge,actual,Mouse(),Memory())));
        var ambiguous=Clone(actual);ResidentWire.Map(ambiguous["match_margin"])["next_state_distance"]=.9;Check("matching_unapproved_competing_state_blocks_reflex",()=>Throws(()=>vision.VerifyReflex(binding,ambiguous,Mouse(),Memory())));
        var missing=Clone(negative);ResidentWire.Map(((object[])missing["skills"])[0])["negatives"]=new object[0];Check("missing_known_state_negative_not_qualified",()=>!Qualified(Match(Load(snapshot,missing),scene)));
        var failed=Clone(negative);var failedRow=ResidentWire.Map(((object[])ResidentWire.Map(((object[])failed["skills"])[0])["negatives"])[0]);failedRow["matched"]=true;failedRow["pass"]=false;Check("matching_other_state_not_qualified",()=>!Qualified(Match(Load(snapshot,failed),scene)));
        var self=Clone(snapshot);var selfSkill=ResidentWire.Map(((object[])self["skills"])[0]);selfSkill["review"]=ResidentWire.Obj("status","approved","reviewer","self");ResidentWire.Map(selfSkill["signature"])["review"]=selfSkill["review"];var selfGuard=ResidentWire.Map(ResidentWire.Map(selfSkill["signature"])["modal_guard"]);selfGuard.Remove("review");selfSkill["modal_guard"]=selfGuard;var selfNegative=Negative(self);ResidentWire.Map(((object[])selfNegative["skills"])[0])["audit_reviewer"]=null;ResidentWire.Map(((object[])selfNegative["skills"])[0])["approved_audit_sha256"]=null;Check("self_adopted_source_with_objective_evidence_needs_no_human_report",()=>Qualified(Match(Load(self,selfNegative),scene)));
        var rejected=Clone(snapshot);var rejectedSkill=ResidentWire.Map(((object[])rejected["skills"])[0]);rejectedSkill["review"]=ResidentWire.Obj("status","rejected","reviewer","user");ResidentWire.Map(rejectedSkill["signature"])["review"]=rejectedSkill["review"];Check("user_rejected_source_never_reflects",()=>!Qualified(Match(Load(rejected,Negative(rejected)),scene)));
        var revoked=Clone(negative);ResidentWire.Map(((object[])revoked["skills"])[0])["user_revoked"]=true;Check("user_revoked_blocks_self_adoption",()=>!Qualified(Match(Load(snapshot,revoked),scene)));
        var weakHistory=Clone(snapshot);ResidentWire.Map(ResidentWire.Map(ResidentWire.Map(((object[])weakHistory["skills"])[0])["governance"])["metrics"])["distinct_runs"]=1;Check("one_run_cannot_qualify_even_with_sidecar_pass",()=>!Qualified(Match(Load(weakHistory,Negative(weakHistory)),scene)));
        var frozen=Clone(negative);ResidentWire.Map(((object[])frozen["skills"])[0])["activation_frozen"]=true;Check("frozen_entry_not_qualified",()=>!Qualified(Match(Load(snapshot,frozen),scene)));
        var changedSignature=Clone(negative);ResidentWire.Map(((object[])changedSignature["skills"])[0])["signature_sha256"]=Sha("other");Check("signature_revision_mismatch_not_qualified",()=>!Qualified(Match(Load(snapshot,changedSignature),scene)));
        var changedTemplate=Clone(snapshot);changedTemplate["source_knowledge_sha"]=negative["snapshot_sha256"];var changedPart=ResidentWire.Map(ResidentWire.Map(((object[])changedTemplate["skills"])[0])["signature"]);var rgb=Convert.FromBase64String((string)changedPart["rgb_base64"]);rgb[0]--;changedPart["rgb_base64"]=Convert.ToBase64String(rgb);changedPart["template_sha256"]=ResidentWire.Hash(rgb);Check("compact_template_swap_cannot_reuse_signature_sha",()=>!Qualified(Match(Load(changedTemplate,negative),scene)));
        var changedElement=Clone(snapshot);changedElement["source_knowledge_sha"]=negative["snapshot_sha256"];ResidentWire.Map(ResidentWire.Map(((object[])changedElement["skills"])[0])["element"])["bbox"]=Box(120,24,64,32);Check("compact_action_swap_cannot_reuse_audit",()=>!Qualified(Match(Load(changedElement,negative),scene)));
        var changedGuard=Clone(snapshot);changedGuard["source_knowledge_sha"]=negative["snapshot_sha256"];ResidentWire.Map(ResidentWire.Map(ResidentWire.Map(((object[])changedGuard["skills"])[0])["signature"])["modal_guard"])["expected_panels"]=new object[]{Box(120,72,144,88)};Check("compact_guard_swap_cannot_reuse_audit",()=>!Qualified(Match(Load(changedGuard,negative),scene)));
        var unknown=(byte[])scene.Clone();Paint(unknown,new Rectangle(120,72,144,88),20,20,20);var modal=Match(vision,unknown);Check("unknown_dark_modal_detected_despite_signature_match",()=>ResidentWire.Text(modal,"status")=="known"&&ResidentWire.Text(ResidentWire.Map(modal["modal"]),"status")=="present"&&Throws(()=>vision.VerifyReflex(binding,modal,Mouse(),Memory())));
        var bright=(byte[])scene.Clone();Paint(bright,new Rectangle(120,72,144,88),240,240,240);Check("unknown_light_modal_detected",()=>ResidentWire.Text(ResidentWire.Map(Match(vision,bright)["modal"]),"status")=="present");
        var expected=new object[]{Box(120,72,144,88)};Check("reviewed_actual_panel_geometry_clear",()=>ResidentWire.Text(UiSkillVision.CheckModal(unknown,Width,Height,expected),"status")=="clear");Paint(unknown,new Rectangle(112,64,160,112),20,20,20);Check("expanded_known_panel_rejected",()=>ResidentWire.Text(UiSkillVision.CheckModal(unknown,Width,Height,expected),"status")=="present");
        var noGuard=Clone(snapshot);ResidentWire.Map(ResidentWire.Map(((object[])noGuard["skills"])[0])["signature"]).Remove("modal_guard");Check("guard_unsupported_never_reflex",()=>!Qualified(Match(Load(noGuard,Negative(noGuard)),scene)));
        var npc=Clone(snapshot);ResidentWire.Map(ResidentWire.Map(((object[])npc["skills"])[0])["element"])["purpose"]="talk_jaina_layered";Check("fixed_npc_element_never_qualifies_reflex",()=>!Qualified(Match(Load(npc,Negative(npc)),scene)));
        var competing=Clone(snapshot);var pending=ResidentWire.Map(((object[])competing["skills"])[1]);pending["status"]="pending_review";var pendingSig=ResidentWire.Map(pending["signature"]);var sourceSig=ResidentWire.Map(ResidentWire.Map(((object[])competing["skills"])[0])["signature"]);pendingSig["rgb_base64"]=sourceSig["rgb_base64"];pendingSig["template_sha256"]=sourceSig["template_sha256"];pendingSig["review"]=ResidentWire.Obj("status","pending","reviewer","unreviewed");var competingCurrent=Match(Load(competing,null),scene);Check("unapproved_template_compares_but_never_recognizes",()=>ResidentWire.Text(competingCurrent,"status")=="known"&&ResidentWire.Text(competingCurrent,"state_id")=="state-a"&&ResidentWire.Num(competingCurrent,"confidence")==0&&ResidentWire.Num(ResidentWire.Map(competingCurrent["match_margin"]),"next_state_distance")==0);
        var perturbed=(byte[])scene.Clone();Paint(perturbed,new Rectangle(16,16,64,32),208,23,18);double confidence=ResidentWire.Num(actual,"confidence"),less=ResidentWire.Num(Match(vision,perturbed),"confidence");Check("confidence_uses_actual_match_margin",()=>confidence>less&&less>0&&confidence!=.95);
        var hard=Clone(snapshot);var hardSkill=Skill("stop","innocent-renamed-state",210,25,20,"pending_review");hardSkill["hard_stop"]=true;var hardSig=ResidentWire.Map(hardSkill["signature"]);hardSig["review"]=ResidentWire.Obj("status","rejected","reviewer","unreviewed");hard["skills"]=new object[]{((object[])hard["skills"])[0],((object[])hard["skills"])[1],hardSkill};Check("matching_hard_stop_loaded_without_approval_or_label_regex",()=>ResidentWire.Bool(Match(Load(hard,null),scene),"hard_stop"));
        var bad=Clone(snapshot);var malformed=Skill("bad","bad-state",210,25,20,"candidate");ResidentWire.Map(malformed["signature"])["template_sha256"]=Sha("wrong");bad["skills"]=new object[]{((object[])bad["skills"])[0],((object[])bad["skills"])[1],malformed};var isolated=Load(bad,null);Check("bad_signature_quarantined_other_state_still_matches",()=>isolated.Quarantine.Count==1&&ResidentWire.Text(Match(isolated,scene),"status")=="known");
        var generic=Clone(snapshot);ResidentWire.Map(((object[])generic["skills"])[0])["state_id"]="in_world";Check("generic_in_world_tutorial_reference_not_accepted",()=>ResidentWire.Text(Match(Load(generic,null),scene),"status")=="unknown");
        var key=Clone(snapshot);ResidentWire.Map(((object[])key["skills"])[0])["action"]=ResidentWire.Obj("kind","key","keys",new object[]{"ESC"},"duration_ms",120);var keyVision=Load(key,Negative(key));var keyMatch=Match(keyVision,scene);var keyBinding=ResidentWire.Obj("skill_id","a","route","reflex","knowledge_sha256",keyVision.KnowledgeSha);var keyAction=ResidentWire.Obj("kind","timeline","duration_ms",120,"events",new object[]{ResidentWire.Obj("kind","key_down","at_ms",0,"key","ESC"),ResidentWire.Obj("kind","key_up","at_ms",120,"key","ESC")});
        Check("reviewed_key_primitive_does_not_grant_mouse",()=>{keyVision.VerifyReflex(keyBinding,keyMatch,keyAction,Memory());return Throws(()=>keyVision.VerifyReflex(keyBinding,keyMatch,Mouse(),Memory()));});
        Console.WriteLine(ResidentWire.Encode(ResidentWire.Obj("protocol","wow-native-ui-governance-pure-fixture","version",1,"desktop_access",false,"input_events",0,"live_confirmation",false,"passed",Results.Count,"modal_algorithm_sha256",UiSkillVision.ModalAlgorithmSha(),"cases",Results)));return 0;
    }catch(Exception error){Console.WriteLine(error.GetType().Name+":"+error.Message+"\n"+error.StackTrace);return 1;}}
}
